fix: no more pytest generated files in my directory
Clinical-Genomics/BALSAMIC pull request #1093
Opened 2023-02-13 16:47 UTC by ivadym

### This PR:

Removed:
* Pytest file saved in balsamic directory

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2023-02-15 07:52 UTC, fevac requested changes
🌟 🌟

2023-02-15 07:52 UTC, fevac commented on tests/commands/plugins/conftest.py
> +    return tmp_path / "test_createVCF_output.vcf.gz"
```suggestion
    return Path(tmp_path, "test_createVCF_output.vcf.gz").as_posix()
```

2023-02-15 08:21 UTC, ivadym commented on tests/commands/plugins/conftest.py
> +    return tmp_path / "test_createVCF_output.vcf.gz"
🕺

2023-02-16 12:31 UTC, fevac approved these changes

2023-02-20 12:25 UTC, merged