perf: Update python version and its dependencies
Clinical-Genomics/BALSAMIC pull request #1216
Opened 2023-08-04 11:53 UTC by ivadym

### This PR:

## Changed:
- Updated Python version to 3.11 and its dependencies 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2023-08-08 11:39 UTC, ivadym commented
Ready for review @Clinical-Genomics/cancer-bioinfo!

After I merge it into develop, please make sure you update your environment accordingly

2023-08-09 11:57 UTC, fevac requested changes

2023-08-09 11:57 UTC, fevac commented on setup.py
> +    version="12.0.2",
do we want to have this fixed?

2023-08-09 11:57 UTC, fevac commented on tests/commands/init/test_init.py
> +    with mock.patch.object(Source, "render", side_effect=BalsamicError("Test error")):
I didn't know this

2023-08-09 11:57 UTC, fevac commented on tests/commands/init/test_init.py
> +    # THEN the human reference generation workflow should have been canceled
should fail?

2023-08-09 11:59 UTC, fevac commented
Nice! 🌟 I forgot to add the review comment at the end 😬 I'm skeptical about fixing the version string. The rest looks good to me!

2023-08-09 12:38 UTC, khurrammaqbool approved these changes
Nice work 👍 
I have some minor comments. I suggest fixing python down to the minor version and please make sure `tomli` behaves as intended with `toml` by running a case. Since python version effects many dependencies, it will be nice to test the installation of `BALSAMIC` in a new conda environment to make sure all the dependencies are resolved.

2023-08-09 12:38 UTC, khurrammaqbool commented on .readthedocs.yml
> +    python: "3.11"
I suggest fixing the minor version as well to to avoid fails/debugging after minor versions automatically updating during builds.

2023-08-09 12:38 UTC, khurrammaqbool commented on setup.py
> +    "tomli==2.0.1",
Could you please run a case to make sure that the behaviour of toml functions is not changed.

2023-08-09 14:06 UTC, ivadym commented on tests/commands/init/test_init.py
> +    # THEN the human reference generation workflow should have been canceled
👍

2023-08-09 14:11 UTC, ivadym commented on setup.py
> +    version="12.0.2",
We are not fixing it, if you check the updated `.bumpversion.cfg` file, I've added this file there. So now it will be automatically updated to the deployment version when making the release.

https://github.com/Clinical-Genomics/BALSAMIC/blob/fd98ed2bf7df84eda878a868a727cdf3c39dfb95/.bumpversion.cfg#L24-L28

2023-08-09 14:11 UTC, ivadym commented on setup.py
> +    version="12.0.2",
In CG I believe we follow the same strategy 😇

2023-08-09 14:14 UTC, ivadym commented on setup.py
> +    "tomli==2.0.1",
I've run a TN-WGS and a TN-panel case, and both finished successfully. The `toml` version is the same, I've just added more dependencies to the setup.py :)

2023-08-09 14:59 UTC, ivadym commented on .readthedocs.yml
> +    python: "3.11"
Then we'll have to require users to have a very strict version of python ("==3.11.0"), which I don't think it's a good idea. Probably a better solution is to keep our dependancies up to date and revisit them more often.

2023-08-10 08:15 UTC, fevac commented on setup.py
> +    version="12.0.2",
the things I learn from you!! 🌟

2023-08-10 08:18 UTC, fevac approved these changes
🚀

2023-08-10 08:32 UTC, merged

2023-08-10 08:43 UTC, khurrammaqbool commented on .readthedocs.yml
> +    python: "3.11"
As you mentioned "revisit them", I am thinking the same. Fixing the "major.minor.patch" for python, and dependencies, with the current "tested" version when we revisit the dependencies. We should manually update this instead of letting it updated automatically by not fixing it down to patch version. As we have seen in the past that sometimes the patch version can fail and we have to wait at least a couple of days for the developers to fix it if it originates in those dependencies, which could happen while deploying as well. This will potentially cause unnecessary delays for development, testing and deployment and compromise the robustness to some extent. I agree that the downside will be to visit it again, but we were using 3.7 for very long time until it is deprecated so it may be nice to have some schedule for revisiting the versions instead of only fixing them when they require fixing or get deprecated.  
Also, we have fixed all the dependencies to patch level. The same argument applies to the version of python as well. There is a tradeoff between having robustness vs using the latest, which could be balanced with proper implementation of schedules for the updates.

2023-08-10 09:33 UTC, ivadym commented on .readthedocs.yml
> +    python: "3.11"
I believe its significance in this context is somewhat diminished, primarily because we have the Python version locked in our environment. For GitHub actions or docs, the only places where the Python version isn't fixed, I think it's unlikely that an updated version will break them. If you have a strong opinion regarding this we can change it