added values for HSMETRICS_QC_CHECK
Clinical-Genomics/BALSAMIC pull request #401
Opened 2020-09-02 12:50 UTC by keyvanelhami

### This PR:

This PR addresses issue #394 .

Added: New dictionary is added where the required QC parameters for the Balsamic analysis to pass, are added with different values for different bait sets. 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2020-09-02 12:52 UTC, keyvanelhami commented
@hassanfa Please review the newly added "HSMETRICS_QC_CHECK" in the j.son file. Does it looks like a good procedure?

2020-09-02 12:57 UTC, hassanfa commented
Awesome! What do you think about having versions in panel bed names? I mean it can be useful to have it so we can track them back. But I don't think it matters which panel version it is, what do you think?

2020-09-03 06:15 UTC, keyvanelhami commented
@hassanfa I think it's important to include the bed versions, and I have already added it to the bed name, e.g. `gmck_solid_4.1`. Or do you mean something else with bed versions?

2020-09-08 11:36 UTC, hassanfa commented
Been thinking about this for a while, and if we need to have control over the version for panel, we could use a structure such as the following:
```
QC_METRICS = {
	'gi_cfdna_3.1': {
		'MEAN_TARGET_COVERAGE': 500,
		'FOLD_80_BASE_PENALTY': 1.5,
		'PCT_OFF_BAIT': 0.35
	},
	'wes': {
		'MEAN_TARGET_COVERAGE': 500,
		'FOLD_80_BASE_PENALTY': 1.5,
		'PCT_OFF_BAIT': 0.35
	},
	'wgs': {
		'FOLD_80_BASE_PENALTY': 1.5,
		'PCT_OFF_BAIT': 0.35
	}
}
```

We could mix and match QC_METRICS based on panel we have. So key names will be panel names, or application type. It could be WGS, WES, RNA, or even specific panel name such as `gi_cfdna_3.1`.

2020-09-11 12:37 UTC, ashwini06 approved these changes
few comments

2020-09-11 12:37 UTC, ashwini06 commented on BALSAMIC/utils/constants.py
> +    'gi_cfdna_3.1': {
just for consistency 'gi_cfdna_3.1' -> "gi_cfdna_3.1"

2020-09-11 12:37 UTC, ashwini06 commented on BALSAMIC/utils/constants.py
> +        "MEAN_TARGET_COVERAGE": 30,
Is other params missing here for wgs?

2020-09-11 12:39 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +        "MEAN_TARGET_COVERAGE": 30,
Agreed, we need to expand WGS features.

2020-09-29 19:29 UTC, hassanfa commented
I changed the base branch to develop from master.

2020-10-02 09:01 UTC, keyvanelhami commented
@ashwini06 @hassanfa I pushed a python script `qc_check.py` that provides a table with qc check for samples from the HS metrics. I know there is room for a lot of improvements. Please have a look at the script and provide som feedback.

2020-10-02 09:31 UTC, hassanfa requested changes
Nice work! I really liked the smart way of converting it to DataFrame instead. I added some general comments and some specific ones. We can use this script as it is, but it will be hard to integrate it to rest of BALSAMIC and Snakemake workflows.

Quality of code changes:

1. Update docstring and type hinting on the new functions
1. Add some unit tests so coverage doesn't drop more than 0.5%
1. Some code style change on empty lines etc (this can be done as last step of this pull request)


Logic and rational of what needs to be done:

1. Preferably this pull request should address the need for being able to check if an analysis has passed quality control metrics. These metrics can be diverse values for each panel, whole exome, or whole genome runs. Current implementation might make it challenging to add to rest of BALSAMIC. So it has to be a non-Click implementation.
1. The logic for `check_qc_criteria` is too specific. Expanding this feature should be easy in future. I suggest to just compare between the values set in `HSMETRICS_QC_CHECK` and actual input.

To address both points above I suggest the following:
Step 1. Find the path to `multiqc_picard_HsMetrics.json` in an analysis directory
Step 2. Convert it to a DataFrame
Step 3. Convert `HSMETRICS_QC_CHECK` to DataFrame
Step 4. Compare matching values in `HSMETRICS_QC_CHECK` DataFrame to values in `multiqc_picard_HsMetrics.json` DataFrame
Step 5. Extract Capture kit name from analysis config
Step 6. Filter out only matching column of capture kit with result from Step 4.

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +qc_list = ['MEAN_TARGET_COVERAGE', 'FOLD_80_BASE_PENALTY', 'PCT_OFF_BAIT']
1. Move this to `BALSAMIC/utils/constants.py` and then import it here: `from BALSAMIC.utils.constants import QC_LIST`
1. Lets have a descriptive variable name here. And being a constant/global, lets have it upper case `qc_list` --> `BASE_QUALITY_METRICS`

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +
```suggestion
```

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +def read_hs_metrics(hs_metrics_file):
Add type hinting:
```suggestion
def read_hs_metrics(hs_metrics_file: str):
```

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +    '''
Please use the following format for all other functions below.

```suggestion
    ''' Reads the HS metrics (json-format) and returns it as a DataFrame
    
    Args:
        hs_metrics_file: A string path to the file

    Returns:
        metrics_df: DataFrame
    '''
```

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +
```suggestion
```

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +    '''
Similar to previous functions, please update:
1. Typehint
1. Docstring

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +
```suggestion
```

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +    '''
Please update docstring similar to read_hs_metrics example above.

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +def get_bait_name(input_df):
bait set name is known from config file. It can be extracted from config file. Have a look at one of the configs generated by BALSAMIC, and there is a field where filename exists.

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +    '''
Similar to previous functions, please update:
1. Typehint
2. Docstring

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +    '''
Same here. Similar to previous functions, please update:
1. Typehint
1. Docstring

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +def check_qc_criteria(input_qc_df, input_hsmetrics_df):
I'll add a general comment about this function in main review. In summary, it should just check values regardless of what it is. For example, one doesn't need to specifically ask for MEAN_TARGET_COVERAGE.

2020-10-02 09:31 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +    main()
Great that you have this script with a Click functionality. It is preferable to have this as part of rest of BALSAMIC as well.

Perhaps it is better if you can remove Click, and have a `qc_check()`, so we can import it somewhere else?

Example:
```
from BALSAMIC.utils import qc_check

qc_check_summary  = qc_check(......)
```

This way we can use this script in a Snakemake rule and in CLI as well.

2020-10-02 12:31 UTC, keyvanelhami commented on BALSAMIC/utils/qc_check.py
> +def read_hs_metrics(hs_metrics_file):
How his type hinting used for DataFrames?

2020-10-02 12:59 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +def read_hs_metrics(hs_metrics_file):
example: 
```
import pandas

def some_function(my_df: pandas.DataFrame) -> pandas.DataFrame:
     ...

```

2020-10-02 13:00 UTC, hassanfa commented on BALSAMIC/utils/qc_check.py
> +def read_hs_metrics(hs_metrics_file):
`-> pandas.DataFrame` is to typehint return.

2020-10-12 13:59 UTC, keyvanelhami commented
I have now pushed following changes:

- Updated docstring and typehint for every function
- Rewrote the `check_qc_criteria` function according to comments from Hassan.
- Added two new functions: `failed_qc` and `write_output`

What remains:

- [ ] Rewrite `get_bait_name` to extract the bait name from config file instead
- [ ] Add unit test 
- [ ] Make the script compatible to run with Balsamic CLI by removing e.g. click 

@hassanfa please have a look and let me know if I have missed anything.

2020-10-13 07:09 UTC, hassanfa commented
@keyvanelhami Good plan!

2020-10-20 13:20 UTC, keyvanelhami commented
@hassanfa regarding the above bullet point `Rewrite get_bait_name to extract the bait name from config file instead`. Right now I am extracting this information from the hs_metrics.json. Why should we extract this information from the config instead? I can't see the point

2020-10-22 12:03 UTC, keyvanelhami commented
@hassanfa Please look into the final script. Also comment how I could improve my code if case is analyzed as single.

2020-10-23 06:00 UTC, hassanfa commented
Well done ✨✨

Let's fix:
1. autostyle using yapf/black in your pycharm, and good to go.
2. Some more test coverage. We are at 99%, would be cool to have it as close to it as possible.

It would be important to fix these for the next PR when you integrate this to the rest of BALSAMIC.

2020-10-26 13:05 UTC, hassanfa requested changes
Final changes and we are a go! Lets hope tests cover enough not to drop more than 1% 😁 Otherwise more tests 😁

2020-10-26 13:05 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    hs_metrics_path = "/Users/keyvan.elhami/Downloads/multiqc_picard_HsMetrics.json"
could you add these as fixture to `tests/test_data/qc_files/`? and then change this line?

2020-10-26 13:05 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    qc_table_path = "/Users/keyvan.elhami/Downloads/qc_table4.json"
Same here: could you add these as fixture to `tests/test_data/qc_files/`? and then change this line?

2020-11-03 06:54 UTC, hassanfa approved these changes
Wonderfully done Keyvan!

I particularly liked how the tests were arranged, `assert some_condisiton, "message"` was a nice touch, addition of two test json files was also smart.

Please fix the comments below and hit that merge button.

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +def test_get_bait_and_sample_name():
use `tumor_normal_wgs_config ` fixture here.

```suggestion
def test_get_bait_and_sample_name(tumor_normal_wgs_config):
```

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    sample_name = get_sample_name(config_file)
```suggestion
    # GIVEN a tumor_only case config
    # WHEN reading the file
    bed = get_bait_name(tumor_normal_wgs_config)
    sample_name = get_sample_name(tumor_normal_wgs_config)
```

2020-11-03 06:54 UTC, hassanfa commented on tests/test_data/qc_files/config_paired.json
> +{
could you rename this to case_config_tumor_normal.json ? It is more descriptive and matching.

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    output_path = "tests/test_data/qc_files/output.csv"
Use PyTest's temporary path factory here:
```suggestion
def test_check_qc_criteria_output_csv_and_qc(tmp_path):
    # GIVEN following variables
    config_file = "tests/test_data/qc_files/config_paired.json"
    hs_metrics = "tests/test_data/qc_files/multiqc_picard_HsMetrics.json"
    
    test_new_dir = tmp_path / "check_qc_results" / "output.csv"
    test_new_dir.mkdir()
    output_path = test_new_dir / "config.json"
```

then `output_path.as_posix()` or `str(output_path)` is the one to use below in assert.

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    assert os.path.isfile(output_path), "File doesn't exists"
```suggestion
    assert output_path.exists(), "File doesn't exists"
```

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    assert len(nr_of_indexes) == 3, "number of indexes != 3"
Failing to test below will already break tests

```suggestion
    assert len(nr_of_indexes) == 3
```

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +import os
import pathlib
```suggestion
import os
from pathlib import Path
```

2020-11-03 06:54 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +        print("File doesn't exist")
Use import here instead of try/except
```python
from BALSAMIC.utils....
```

2020-11-11 08:19 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +def test_get_bait_and_sample_name():
@hassanfa should tumor_normal_wgs_config be a global variable? Or how should this value be provided in the function?

2020-11-11 09:36 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +    output_path = "tests/test_data/qc_files/output.csv"
Where is `tmp_path` provided when running the pytest?

2020-11-11 09:36 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +def test_get_bait_and_sample_name():
`tumor_normal_wgs_config` is a `scope="session"` fixture. It is available throughout all tests: https://docs.pytest.org/en/stable/fixture.html#conftest-py-sharing-fixture-functions Fixtures are quite handy in testing stuff, mocking, etc.

There are four fixture for configs: `tumor_normal_config`, `tumor_only_config`, `tumor_normal_wgs_config`, and `tumor_only_wgs_config`. You can use them in every tests.

2020-11-11 09:42 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    output_path = "tests/test_data/qc_files/output.csv"
`tmp_path` is also a fixture, this is provided by pytest. very handy to create temporary path and files.

2020-11-11 10:47 UTC, keyvanelhami commented on tests/test_data/qc_files/config_paired.json
> +{
Done!

2020-11-11 10:47 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +    sample_name = get_sample_name(config_file)
Done!

2020-11-11 10:47 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +def test_get_bait_and_sample_name():
Done!

2020-11-11 11:03 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +    output_path = "tests/test_data/qc_files/output.csv"
Why do you use "config.json" in `output_path`? The `output_path` variable is used in the `write_output` function and should not be config-file, it should just indicate where to put the output.csv file

2020-11-12 07:43 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    output_path = "tests/test_data/qc_files/output.csv"
My mistake, I meant "output.csv" or something similar.

So it should be:

```python
test_new_dir = tmp_path / "check_qc_results"
test_new_dir.mkdir()
output_path = Path(test_new_dir / "output.csv").as_posix()
```

2020-11-12 07:55 UTC, hassanfa commented on tests/utils/test_qc_check.py
> +    output_path = "tests/test_data/qc_files/output.csv"
tmp_path and `mkdir()` build the temporary directory and return a `Path` object. `write_output` doesn't support `Path`objects, that's why I added `as_posix()`. One can use `str()` as well.

2020-11-12 09:28 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +    assert len(nr_of_indexes) == 3, "number of indexes != 3"
Done

2020-11-12 09:28 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +import os
Done

2020-11-12 09:28 UTC, keyvanelhami commented on tests/utils/test_qc_check.py
> +        print("File doesn't exist")
Done

2020-11-12 10:11 UTC, keyvanelhami commented
@hassanfa Please have a final look and then merge :)

2020-11-12 15:15 UTC, hassanfa commented
Coverage 0.4%, but we need this feature so merging it.

2020-11-12 15:15 UTC, merged