Features: Adds qc rules to UMI workflow
Clinical-Genomics/BALSAMIC pull request #431
Opened 2020-09-29 12:47 UTC by ashwini06

### This PR 
Corresponds to issue 2 in [cg-cancer-umi ](https://github.com/Clinical-Genomics/cgp-cancer-umi/issues/2)

**Added:** 

1.  Rules to calculate QC measures for UMI workflow. Implementation includes:
       
     - [x] Picard UmiAware
       
     - [x] Picard HSmetrics

     - [x] Noise Allele frequency       

     - [x]  Density plots for Allelic frequency distribution

2. config JSON file includes `SENTIEON_INSTALL_DIR` and `SENTIEON_LICENSE"`

3. Thread parameters for the UMI rules in cluster.json file

**Changed:** 
Added wildcard {step} to variant calling and vep rules 
Initially, UMIextract bwa_alignment outputs the` sam` file. Now changed to `bam`

**Execution:**
`balsamic run analysis --sample-config demo/fairsalmon2/fairsalmon2.json --run-mode local --snakemake-opt "--cores 8" -a umi --run-analysis`

<img width="1221" alt="Screenshot 2020-09-29 at 12 30 57" src="https://user-images.githubusercontent.com/6302819/94558189-edd15600-025f-11eb-9bc7-f9cb51241669.png">

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2020-09-29 19:26 UTC, hassanfa requested changes
👍🏽 I know it is a draft, but I couldn't resist ;-)

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/commands/config/case.py
> +	SENTIEON_LICENSE="10.10.10.1:8990",
Could we get these from env variables? What will happen if environment variables don't exist? Otherwise, set it in the workflow instead. Similar to other workflows.

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +        mrkdup = qc_dir + '{sample}.{step}.collect_hsmetric'
```suggestion
        mrkdup = qc_dir + '{sample}.{step}.collect_hsmetric_umi'
```

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +        benchmark_dir + "{sample}.{step}.collect_hsmetrics.tsv"
```suggestion
        benchmark_dir + "{sample}.{step}.collect_hsmetrics_umi.tsv"
```

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +rule noise_AF:
Interesting approach, I like it! Lets see how it will perform.

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +        SENTIEON_LICENSE:Field(str); sentieon license number
UMI changing often, maybe we can remove these and keep them in workflow for now? If you add them here, it might force your hand into fixing things that are not related to UMI.

It can be set on runtime in workflow. For example see: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/workflows/VariantCalling_sentieon.smk line35-43.

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/utils/umiplots.py
> +    return (plt.savefig(output_file))
You can move the whole thing into the rule. Otherwise, write a test for it 😛

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/utils/umiplots.py
> +import sys
Seems like `sys` is not used.

2020-09-29 19:26 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +        SENTIEON_LICENSE:Field(str); sentieon license number
Also, i see that they are already set in workflow. If you've changed this due to my comment, I apologize. I might not have noticed it. `UMIWorkflow.smk` already has it set.

2020-09-29 19:28 UTC, hassanfa commented
I changed the base branch to develop from master.

2020-10-01 12:37 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +rule noise_AF:
Not the best approach, I worry about the computation time. If I come up with an alternative solution I will change it :)

2020-10-02 08:09 UTC, ashwini06 commented
@hassanfa Thank you for your comments on draft. I fixed all those, can you please have a look again.

2020-10-02 08:33 UTC, hassanfa approved these changes
Looks good!

2020-10-02 08:33 UTC, hassanfa commented
⭐  Merging it!

2020-10-02 08:33 UTC, merged