Feat/filterconsensus called reads
Clinical-Genomics/BALSAMIC pull request #469
Opened 2020-10-21 15:53 UTC by ashwini06

### This PR is a combination of changes:

Added:

- [x] Bash script to filter Consensuscalled reads based on XZ tag. By default, the parameter `min read` is to set to `'3,1,1'` for filtering. 
       - Helps to reduce the number of false-positives from variant-calling. It still needs to identify the best `minreads` settings and check for recall/precision values.

- [x] Refactoring of `sentieon_consensuscall` rule in UMI_workflow
         - Restructured snakemake rule structure and defining the names. Updated cluster.json for the correct rule name
         - Removed the declaration of parameter values in rules. Instead, moved declaration to constant.py,  

## Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2020-10-21 20:18 UTC, hassanfa commented
Let me know when it is ready to review.

2020-10-22 15:24 UTC, ashwini06 commented
> Let me know when it is ready to review.

@hassanfa Now it's ready for review

2020-10-23 05:46 UTC, hassanfa requested changes
✨✨
Some minor comments.

2020-10-23 05:46 UTC, hassanfa commented on BALSAMIC/assets/scripts/FilterDuplexUMIconsensus.sh
> +awk -v MinR=$min_reads -v OFS="\t" '
Could we add this as awk script? We can then move rest of it to snakemake shell. 

Reason is, this script has to be moved into a python, R, or Go script for maintainability in future.

2020-10-23 05:46 UTC, hassanfa commented on BALSAMIC/config/cluster.json
> +	"sentieon_umi_align": {
Do UMI rules need 24:00:00? Let's reduce this to a lower number. What do you recommend?

2020-10-23 05:46 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
> +        benchmark_dir + '{sample}.{var_caller}.AFcalculate.tsv'
Could we have rule name first for benchmark file.

2020-10-23 05:46 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule
> +from BALSAMIC.utils.models import UMIworkflowConfig
Wonderful!

2020-10-23 05:46 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +class UMIworkflowParams(BaseModel):
Please add attributes to docstring as well.

2020-10-23 05:46 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +class UMIworkflowConfig(BaseModel):
Please extend docstring.

2020-10-23 06:58 UTC, hassanfa commented
Forgot to mention, please also add tests for two new models you've added in https://github.com/Clinical-Genomics/BALSAMIC/blob/master/tests/utils/test_models.py

2020-10-23 14:07 UTC, ashwini06 commented on BALSAMIC/assets/scripts/FilterDuplexUMIconsensus.sh
> +awk -v MinR=$min_reads -v OFS="\t" '
yes changed to awk script.

2020-10-23 14:08 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
> +        benchmark_dir + '{sample}.{var_caller}.AFcalculate.tsv'
Fixed

2020-10-26 08:08 UTC, hassanfa approved these changes
Very nice! ⭐  ⭐  I liked addition of the parameters to constants. At some point we need to move all rule specific params to constants.

2020-10-26 10:51 UTC, ashwini06 commented
> Very nice! ⭐ ⭐ I liked addition of the parameters to constants. At some point we need to move all rule specific params to constants.

Thank you :) Sure, will fix in other PR

2020-10-26 11:58 UTC, merged