Feat:refactor umirules
Clinical-Genomics/BALSAMIC pull request #477
Opened 2020-10-30 08:33 UTC by ashwini06

### This PR:
**Fixed**
- [x] rule structure in all UMI workflow-related snakemake files

**Removed**
- [x] Assigning of params thresholds in the individual rules

**Added**
- [x] Defined params as constants and parsed into the UMI rules
- [x] Tests to check the model classes for UMI rules. 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2020-10-30 16:31 UTC, hassanfa requested changes
Lovely! I specially liked the constant expansion part, expanding models, and meticulous attention to `"` vs `'`.

Some minor comments before we can merge this.

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/annotate_vep.rule
> +        default_options = "--compress_output bgzip --vcf --everything --allow_non_variant --dont_skip --buffer_size 10000 --format vcf --offline --variant_class --merged --cache --verbose --force_ove
👌🏽 
Other VEP rules are also using these options, should we have this as a constant? I don't mind keeping it here though.

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
>  rule generate_backgroundAF_table:
I suggest to match this according to the naming standard we defined:
```suggestion
rule bcftools_query_generate_background_af_table:
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
> +        get_threads(cluster_config, "generate_backgroundAF_table")
```suggestion
        get_threads(cluster_config, "bcftools_query_generate_background_af_table")
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
> +        get_threads(cluster_config, "generate_backgroundAF_table")
This is not in `cluster.json`, and it will be assigned a default core number.

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +rule calculate_meanfamilydepth_umi:
```suggestion
rule samtools_view_calculate_meanfamilydepth_umi:
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +        get_threads(cluster_config, "calculate_meanfamilydepth_umi")
```suggestion
        get_threads(cluster_config, "samtools_view_calculate_meanfamilydepth_umi")
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +rule calculate_noiseAF_umi:
```suggestion
rule bcftools_query_calculate_noise_af_umi:
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +        get_threads(cluster_config, "calculate_noiseAF_umi")
```suggestion
        get_threads(cluster_config, "bcftools_query_calculate_noise_af_umi")
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
>          import matplotlib.pyplot as plt
Is it possible to add this as an standalone script to `BALSAMIC/utils/generate_densityPlots_umi.py`? Then here we just import and provide the function with input and output?

If you think this is outside the scope of this PR, please add it to backlog for another one.

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +rule generate_densityPlots_umi:
I wonder how can we name this to match the new rule name scheme. I suggest one of the following:
1. For this being BALSAMIC script: `balsamic_generate_densityplot_umi`
1. More general wording: `plot_density_umi` (plot being the program, density being the function, and umi being the tag`
1. Specific: `seaborn_densityplot_umi`.

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +        get_threads(cluster_config, "generate_densityPlots_umi")
Remember to change this according to the name.

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> -        get_threads(cluster_config, 'density_Plots')
👍🏽

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +rule sentieon_tnscope_umi:
👌🏽

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +        tAF = paramsumi.common.filter_tumor_af,
I am guilty of using short abbreviations as well. can be expand this please? Please remind me to not use abbreviations as well 😄 

```suggestion
        tumor_af = paramsumi.common.filter_tumor_af,
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +--min_tumor_allele_frac {params.tAF} \
```suggestion
--min_tumor_allele_frac {params.tumor_af} \
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +        TL = config["tumorlod"], #paramsumi.tnscope.min_tumorLOD,
```suggestion
        tumor_lod = config["tumorlod"], #paramsumi.tnscope.min_tumorLOD,
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +--min_init_tumor_lod {params.TL} \
```suggestion
--min_init_tumor_lod {params.tumor_lod} \
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +        detect = paramsumi.tnscope.disable_detect,
```suggestion
        disable_detect = paramsumi.tnscope.disable_detect,
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +--disable_detector {params.detect} \
```suggestion
--disable_detector {params. disable_detect} \
```

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +        "vardict_filters": "-c 1 -S 2 -E 3 -g 4 -r 1 -F 0"
Beautiful! 👌🏽

2020-10-30 16:31 UTC, hassanfa commented on BALSAMIC/workflows/UMIworkflow.smk
> +#STEPS = ["consensusfiltered"]
If we don't use this, can we remove it? Or do you want it to stay for development work?

2020-11-01 19:02 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/annotate_vep.rule
> +        default_options = "--compress_output bgzip --vcf --everything --allow_non_variant --dont_skip --buffer_size 10000 --format vcf --offline --variant_class --merged --cache --verbose --force_ove
Changed as constants. In the future, maybe we should define the global constants that are common to BALSAMIC and UMIs workflows and separate local constants particular to specific workflows.

2020-11-01 19:03 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
>  rule generate_backgroundAF_table:
Thanks for reminding our standard rules. Your suggestion for rule name is clear :)  But I feel it's too biggy. Can we restrict us to 3 words in the rule name, something like this: `bcftools_generatebackgroundaf_table`. What you think?

2020-11-01 19:04 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
> +        get_threads(cluster_config, "generate_backgroundAF_table")
Fixed!

2020-11-01 19:06 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
>          import matplotlib.pyplot as plt
Sure. I will fix it in other PR along with the tests to the standalone script.

2020-11-01 19:06 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/qc_umi.rule
> +rule generate_densityPlots_umi:
I choosed the suggestion 3: `seaborn_densityplot_umi`

2020-11-01 19:07 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +        tAF = paramsumi.common.filter_tumor_af,
Fixed!

2020-11-01 19:07 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +--min_init_tumor_lod {params.TL} \
Fixed!

2020-11-01 19:07 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
> +        detect = paramsumi.tnscope.disable_detect,
Fixed!

2020-11-01 19:09 UTC, ashwini06 commented on BALSAMIC/workflows/UMIworkflow.smk
> +#STEPS = ["consensusfiltered"]
I am playing around while testing. I will remove these two commented lines a bit lateron

2020-11-01 19:53 UTC, hassanfa commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
>  rule generate_backgroundAF_table:
reason for `bcftools_query_XXXXX` was to match it with `<program>_<function>_<tag>` criteria. `generatebackgroundaf` is not exactly function of bcftools. how about: `bcftools_query_generatebackgroundaf`?

2020-11-01 19:55 UTC, hassanfa approved these changes
Merge whenever you feel done. I think it is good to go.

2020-11-02 12:23 UTC, merged