add sample names and propagate to devliverables
Clinical-Genomics/BALSAMIC pull request #520
Opened 2020-12-10 10:35 UTC by Mropat

### This PR:

(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)

Added: for new features.
Changed: for changes in existing functionality.
Deprecated: for soon-to-be removed features.
Removed: for now removed features.
Fixed: for any bug fixes.
Security: in case of vulnerabilities.

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2020-12-10 10:38 UTC, Mropat commented on BALSAMIC/commands/report/deliver.py
> +
Important changes here

2020-12-10 10:39 UTC, Mropat commented on BALSAMIC/commands/config/case.py
> +@click.option("--normal-name", help="Internal ID of normal sample")
important changes here

2020-12-10 10:39 UTC, Mropat commented on BALSAMIC/commands/config/case.py
> +            tumor=tumor, normal=normal, tumor_name=tumor_name, normal_name=normal_name
important changes here

2020-12-10 10:40 UTC, Mropat commented on BALSAMIC/utils/cli.py
> +    tumor: str, normal: str, tumor_name: str = None, normal_name: str = None
improtant changes here

2020-12-10 10:41 UTC, Mropat commented on BALSAMIC/utils/models.py
> +
Important changed here

2020-12-10 17:50 UTC, hassanfa requested changes
Thank you for this PR. 👍🏽 

1. Please unblack the code. use `yapf` there is a style file in repo.
2. travis was failing, and I added develop branch's github action.
3. delivery command for tumor normal failing with following error: `TypeError('string indices must be integers',)`. 
4. Please add a simple test to keep coverage happy :-)

2020-12-10 17:50 UTC, hassanfa commented on BALSAMIC/commands/config/case.py
> +@click.option("--normal-name", help="Internal ID of normal sample")
```suggestion
@click.option("--tumor-sample-name", help="Tumor sample name")
@click.option("--normal-sample-name", help="Normal sample name")
```

2020-12-10 17:50 UTC, hassanfa commented on BALSAMIC/commands/config/case.py
> +@click.option("--normal-name", help="Internal ID of normal sample")
Please change them downstream accordingly.

2020-12-10 17:50 UTC, hassanfa commented on BALSAMIC/commands/report/deliver.py
> +
Could we add a `sample['sample_name"]` instead?

Currently it is as below:
```
    "samples": {
        "S2_R": {
            "file_prefix": "S2_R",
            "sample_id": "S2_R",
            "type": "normal",
            "readpair_suffix": [
                "1",
                "2"
            ]
        },
        "S1_R": {
            "file_prefix": "S1_R",
            "sample_id": "S1_R",
            "type": "tumor",
            "readpair_suffix": [
                "1",
                "2"
            ]
        }
    },
```

Add a key "sample_name" and this way we can avoid using this nested for loops.

2020-12-10 17:51 UTC, hassanfa commented
If yapf is not possible for you, just unblack it, and I'll fix formatting before merge. 👍🏽

2020-12-10 17:51 UTC, hassanfa commented
Oh one more thing, could you run it on actual samples or dummy data and post screenshots? Thanks!

2020-12-11 15:20 UTC, Mropat commented
The output when providing new options:

```
    "samples": {
        "S2_R": {
            "file_prefix": "S2_R",
            "sample_id": "ACC2",
            "type": "normal",
            "readpair_suffix": [
                "1",
                "2"
            ]
        },
        "S1_R": {
            "file_prefix": "S1_R",
            "sample_id": "ACC1",
            "type": "tumor",
            "readpair_suffix": [
                "1",
                "2"
            ]
        }
    },
```

If no options provided, the sample_id is same as prefix

2020-12-11 15:30 UTC, Mropat commented
I also need to test the performance of this when generating a deliverables file. How can I approach testing this?

2020-12-11 16:58 UTC, hassanfa commented
You can install this branch on Hasta on `S_BALSAMIC` .

2020-12-11 16:59 UTC, hassanfa commented
alternatively, you can look here how to use dummy data: https://balsamic.readthedocs.io/en/v6.0.2/user_guide.html

2020-12-11 17:14 UTC, hassanfa commented
> The output when providing new options:
> 
> ```
>     "samples": {
>         "S2_R": {
>             "file_prefix": "S2_R",
>             "sample_id": "ACC2",
>             "type": "normal",
>             "readpair_suffix": [
>                 "1",
>                 "2"
>             ]
>         },
>         "S1_R": {
>             "file_prefix": "S1_R",
>             "sample_id": "ACC1",
>             "type": "tumor",
>             "readpair_suffix": [
>                 "1",
>                 "2"
>             ]
>         }
>     },
> ```
> 
> If no options provided, the sample_id is same as prefix

As mentioned above, I appreciate if you can add a key "sample_name" or just plain "name" to keys above.

If it is confusing, this way the nested for-for-if-if can be reduced just to a tag check in config. Please look here to fix it: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/utils/rule.py#L240

if "sample_name" in config... then swap sample_id to sample_name value.

Please also see my comment on the cli option name and help text.

2020-12-14 13:55 UTC, hassanfa commented on BALSAMIC/commands/report/deliver.py
> +            if sample_config_dict["samples"][sample]["file_prefix"] in file["tag"]:
To make sure there is no unwanted partial string replaced, lets split it by `,`:
```suggestion
if sample_config_dict["samples"][sample]["file_prefix"] in file["tag"].split(","):
```

2020-12-14 13:57 UTC, hassanfa commented
Great that tests passed ⭐ as soon as your tests are finished, I'll make a release and deploy.

2020-12-14 16:31 UTC, Mropat commented
tested making deliverables on dummy data 
```
        {
            "path": "/home/proj/stage/cancer/dummy_balsamic_run/run_tests/TN_WGS/analysis/fastq/S2_R_1.fp.fastq.gz",
            "path_index": [],
            "step": "fastp",
            "tag": "S2,read1,quality-trimmed-fastq-read1",
            "id": "S2",
            "format": "fastq.gz"
        },
        {
            "path": "/home/proj/stage/cancer/dummy_balsamic_run/run_tests/TN_WGS/analysis/fastq/S2_R_2.fp.fastq.gz",
            "path_index": [],
            "step": "fastp",
            "tag": "S2,read2,quality-trimmed-fastq-read2",
            "id": "S2",
            "format": "fastq.gz"
        },
        {
            "path": "/home/proj/stage/cancer/dummy_balsamic_run/run_tests/TN_WGS/analysis/fastq/S1_R_2.fp.fastq.gz",
            "path_index": [],
            "step": "fastp",
            "tag": "S1,read2,quality-trimmed-fastq-read2",
            "id": "S1",
            "format": "fastq.gz"
        },
        {
            "path": "/home/proj/stage/cancer/dummy_balsamic_run/run_tests/TN_WGS/analysis/qc/fastp/S1_R_fastp.json",
            "path_index": [],
            "step": "fastp",
            "tag": "S1,json,quality-trimmed-fastq-json",
            "id": "S1",
            "format": "json"
        },
        {
            "path": "/home/proj/stage/cancer/dummy_balsamic_run/run_tests/TN_WGS/analysis/qc/fastp/S2_R_fastp.json",
            "path_index": [],
            "step": "fastp",
            "tag": "S2,json,quality-trimmed-fastq-json",
            "id": "S2",
            "format": "json"
        },
```

Both "tag" and "id" fields have a new replacement value

2020-12-14 17:13 UTC, hassanfa commented on BALSAMIC/commands/config/case.py
> +@click.option("--normal-sample-name", help="Internal ID of normal sample")
```suggestion
@click.option("--tumor-sample-name", help="Tumor sample name")
@click.option("--normal-sample-name", help="Normal sample name")
```

2020-12-14 17:15 UTC, hassanfa commented on BALSAMIC/commands/report/deliver.py
> +                file["tag"] = (file["tag"].replace(
Per my previous comment, please split tags by `,`. Composit tags are created in Snakemake rules that might include multiple of same sample_id/prefix in tags. I'd like to avoid mistakingly replacing strings that we don't want.

2020-12-14 17:16 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +    sample_name: Optional[str]
Please add sample_name to docstring.

2020-12-14 17:18 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +
expand tests to include this field, just like rest of the values in the model: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/tests/utils/test_models.py

2020-12-14 17:19 UTC, hassanfa commented on BALSAMIC/commands/report/deliver.py
> +                        file_prefix.replace("_", "-"), sample_name))
Coverage dropped from 100% due to these missing lines. Either cover them in cli, or add a new function here.

2020-12-14 19:35 UTC, hassanfa approved these changes

2020-12-14 19:36 UTC, merged