Feat/wgsfilter rules
Clinical-Genomics/BALSAMIC pull request #548
Opened 2021-02-08 08:28 UTC by ashwini06

### This PR:

Adds new rules for filtering WGS TNscope and TNhaplotyper results.
Currently only applicable to tumor-only analysis. 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-02-08 08:43 UTC, ashwini06 commented
Tested on WGS -tumor only case `civilsole`. Check reduction in the number of variants for files for `*.filtered.pass.vcf.gz`
<img width="571" alt="a1" src="https://user-images.githubusercontent.com/6302819/107195479-b171eb80-69f1-11eb-808c-6ea8dc774522.png">

2021-02-08 08:57 UTC, hassanfa commented
Tests are failing for `ModuleNotFoundError: No module named 'setuptools_rust'` We are not using Rust, probably one of the dependencies changed after merging master into develop. I'll check it out.

2021-02-08 09:07 UTC, ashwini06 commented
> Tests are failing for `ModuleNotFoundError: No module named 'setuptools_rust'` We are not using Rust, probably one of the dependencies changed after merging master into develop. I'll check it out.

@hassanfa Locally no issues with the installation
<img width="750" alt="aa2" src="https://user-images.githubusercontent.com/6302819/107198105-02371380-69f5-11eb-9b01-5faba81fa430.png">

2021-02-08 09:38 UTC, hassanfa commented
@ashwini06 try with -U option in pip. 

Apparently `gsutils` is using a new dependency, and that's causing a problem.

2021-02-08 09:56 UTC, ashwini06 commented
> @ashwini06 try with -U option in pip.
> 
> Apparently `gsutils` is using a new dependency, and that's causing a problem.

Indeed. So is it for balsamic report delivery or are we accessing any other resources from cloud?

2021-02-08 09:59 UTC, hassanfa commented
`gsutils` is used on `reference.smk` to download various reference files.

2021-02-08 10:39 UTC, hassanfa commented
@ashwini06 should we merge this and work on optimal threshold values later, or do you prefer to finish it all in this PR?

2021-02-08 10:40 UTC, hassanfa approved these changes
👌🏽

2021-02-09 08:55 UTC, hassanfa requested changes

2021-02-09 08:55 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule
> +| bcftools filter --include 'FORMAT/AD[0:1]+AD[0:1] >= {params.DP[0]}' --soft-filter '{params.DP[1]}' --mode '+' \
This is not correct. According to http://samtools.github.io/bcftools/bcftools.html#expressions it should be:
```suggestion
| bcftools filter --include 'sum(FORMAT/AD[0:1]+FORMAT/AD[0:1]) >= {params.DP[0]}' --soft-filter '{params.DP[1]}' --mode '+' \
```

2021-02-09 08:55 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +        "tag_value": 10,
```suggestion
        "tag_value": 2,
```

2021-02-09 08:55 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +        "tag_value": 0.01,
```suggestion
        "tag_value": 0.05,
```

2021-02-09 09:35 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule
> +| bcftools filter --include 'FORMAT/AD[0:1]+AD[0:1] >= {params.DP[0]}' --soft-filter '{params.DP[1]}' --mode '+' \
Fixed

2021-02-09 09:35 UTC, ashwini06 commented on BALSAMIC/utils/constants.py
> +        "tag_value": 10,
Fixed

2021-02-09 09:35 UTC, ashwini06 commented on BALSAMIC/utils/constants.py
> +        "tag_value": 0.01,
Fixed

2021-02-09 16:47 UTC, hassanfa commented
@ashwini06 I realized I forgot to paste filter string here for posterity. So here it is:

```
 bcftools filter --regions-file callable SNV.somatic.civilsole.tnscope.pass.vcf.gz | bcftools filter --include 'SUM(FORMAT/AD[0:1] + FORMAT/AD[0:0])>10' --mode + --soft-filter filter552 | bcftools filter --include 'FORMAT/AD[0:1]>3 && (FORMAT/ALT_F1R2 > 0  && FORMAT/ALT_F2R1 > 0 &&  FORMAT/REF_F1R2 > 0 && FORMAT/REF_F2R1 > 0) ' --mode + --soft-filter filter112 | bcftools filter --include 'FORMAT/AF[0]>0.05' --mode + --soft-filter filter23123 | bcftools filter --include 'FORMAT/AF < 1' --soft-filter filter4 --mode + | bcftools filter --include 'INFO/GNOMADAF_popmax <= 0.001 || INFO/GNOMADAF_popmax == "."' --mode + --soft-filter filter3 | bcftools filter --include 'SUM(FORMAT/QSS)/SUM(FORMAT/AD) > 20' --mode + --soft-filter filter2 | bcftools view -f PASS | bcftools filter --include "INFO/SOR<2" --mode + --soft-filter blabla | bcftools +counts
```

2021-02-10 11:52 UTC, hassanfa requested changes
👌🏽  Very close to the end.

Added some suggestions to `cnt_reads` and its filter name. Also to `sor` filter name.

I also removed `vcf_pass` from ngs filters tnscope and tnhaplotyper, then by passing `-f PASS` to isec, it'll only take passed variants.

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +|  bcftools filter --include 'FORMAT/ALT_F1R2 > {params.cnt_reads[0]} && (FORMAT/ALT_F1R2 > 0  && FORMAT/ALT_F2R1 > {params.cnt_reads[0]} &&  FORMAT/REF_F1R2 > {params.cnt_reads[0]} && FORMAT/REF_F2R
```suggestion
| bcftools filter --include 'FORMAT/ALT_F1R2 > {params.cnt_reads[0]} && (FORMAT/ALT_F1R2 > 0  && FORMAT/ALT_F2R1 > {params.cnt_reads[0]} &&  FORMAT/REF_F1R2 > {params.cnt_reads[0]} && FORMAT/REF_F2R1 > {params.cnt_reads[0]})' --soft-filter '{params.cnt_reads[1]}' --mode '+' \
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +|  bcftools filter --include 'FORMAT/ALT_F1R2 > {params.cnt_reads[0]} && (FORMAT/ALT_F1R2 > 0  && FORMAT/ALT_F2R1 > {params.cnt_reads[0]} &&  FORMAT/REF_F1R2 > {params.cnt_reads[0]} && FORMAT/REF_F2R
tiny extra space :-)

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    get_threads(cluster_config, 'ngs_filter_intersect')
Is it possible to use threads in bcftools command?

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    benchmark_dir + 'ngs_filter_' + "{var_type}.somatic.{case_name}.vep.tsv"
```suggestion
    benchmark_dir + 'ngs_filter_intersect_' + "{var_type}.somatic.{case_name}.tsv"
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    vcf_name = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.pass.clinical.vcf.gz"
```suggestion
    vcf_pass = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.pass.vcf.gz"
```

This is to make it unified with rest of final housekeeper tags.

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +  params:
```suggestion
  params:
        housekeeper_id = {"id": config["analysis"]["case_id"], "tags": "clinical"},
```

Adds housekeeper tags

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +    "cnt_reads": {
```suggestion
    "strand_reads": {
```

To make it obvious that this is aimed for strand specific counts.

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +	"filter_name": "balsamic_low_read_counts",
```suggestion
	"filter_name": "balsamic_low_strand_read_count",
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/utils/constants.py
> +	"filter_name": "balsamic_sym_or",
```suggestion
	"filter_name": "balsamic_high_strand_oddsratio",
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +|  bcftools filter --include 'FORMAT/ALT_F1R2 > {params.cnt_reads[0]} && (FORMAT/ALT_F1R2 > 0  && FORMAT/ALT_F2R1 > {params.cnt_reads[0]} &&  FORMAT/REF_F1R2 > {params.cnt_reads[0]} && FORMAT/REF_F2R
```suggestion
| bcftools filter --include 'FORMAT/ALT_F1R2 > {params.cnt_reads[0]} && (FORMAT/ALT_F1R2 > 0  && FORMAT/ALT_F2R1 > {params.cnt_reads[0]} &&  FORMAT/REF_F1R2 > {params.cnt_reads[0]} && FORMAT/REF_F2R1 > {params.cnt_reads[0]})' --soft-filter '{params.cnt_reads[1]}' --mode '+' \
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    tnscope = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.pass.vcf.gz",
```suggestion
    tnscope = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.vcf.gz",
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    tnhaplotyper = vep_dir + "{var_type}.somatic.{case_name}.tnhaplotyper.filtered.pass.vcf.gz"
```suggestion
    tnhaplotyper = vep_dir + "{var_type}.somatic.{case_name}.tnhaplotyper.filtered.vcf.gz"
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    vcf_pass = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.pass.vcf.gz",
```suggestion
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +tabix -p vcf -f {output.vcf_pass};
```suggestion
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +tabix -p vcf -f {output.vcf_pass};
```suggestion
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    vcf_pass = vep_dir + "{var_type}.somatic.{case_name}.tnhaplotyper.filtered.pass.vcf.gz",
```suggestion
```

2021-02-10 11:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +bcftools isec {input.tnscope} {input.tnhaplotyper} -p {params.vcf_dir} -O z ;
```suggestion
bcftools isec {input.tnscope} {input.tnhaplotyper} -p {params.vcf_dir} -O z -f PASS;
```

To only take `PASS` variants

2021-02-10 12:51 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    vcf_name = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.pass.clinical.vcf.gz"
@hassanfa : The name will be same as {input.tnscope}.

2021-02-10 12:52 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    vcf_name = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.pass.clinical.vcf.gz"
See my comments on that rule as well. Remove pass from file name:
`tnscope = vep_dir + "{var_type}.somatic.{case_name}.tnscope.filtered.vcf.gz",`

2021-02-10 12:57 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +  params:
@hassanfa how this params is used in bcftools command line?

2021-02-10 14:06 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +  params:
This will be picked up by delivery script, and used there.

2021-02-11 11:36 UTC, hassanfa approved these changes
👍🏽

2021-02-11 11:36 UTC, merged