QC check for balsamic analysis (fold-80 only)
Clinical-Genomics/BALSAMIC pull request #557
Opened 2021-02-12 14:16 UTC by keyvanelhami

Please see issue #504 for instructions

2021-02-12 14:29 UTC, ashwini06 reviewed
remove duplicate function `get_fold80`

2021-02-12 14:29 UTC, ashwini06 commented on BALSAMIC/utils/qc_check.py
> +def get_fold80(hs_metrics: pd.DataFrame) -> pd.DataFrame:
```suggestion
```
duplicate function

2021-02-17 13:41 UTC, hassanfa commented
@keyvanelhami tests are failing with the following error:
```
    from BALSAMIC.utils.qc_check import read_hs_metrics, read_qc_table, check_qc_criteria, write_output
E   ImportError: cannot import name 'read_hs_metrics'
```

2021-02-18 12:27 UTC, hassanfa requested changes
👌🏽  needs some ironing out, but getting closer.

Please also add some tests for the new functions.

2021-02-18 12:27 UTC, hassanfa commented on BALSAMIC/workflows/balsamic.smk
> +        hs_metrics = read_json("/Users/keyvan.elhami/git_repositories/BALSAMIC/tests/test_data/qc_files/multiqc_picard_HsMetrics.json")
`"/Users/keyvan.elhami/git_repositories/BALSAMIC/tests/test_data/qc_files/multiqc_picard_HsMetrics.json"` is not correct. Use `input.hsmetrics[0]` instead. See Snakemake docuemtnation how to use input/output in a rule.

2021-02-18 12:27 UTC, hassanfa commented on BALSAMIC/workflows/balsamic.smk
> +        check_result = check_qc_criteria_simple(fold80_value, "/Users/keyvan.elhami/git_repositories/BALSAMIC/tests/test_data/qc_files/fold_80.txt")
I don't think you can use `/Users/keyvan.elhami/git_repositories/BALSAMIC/tests/test_data/qc_files/fold_80.txt` here either. Pass the correct value instead. Use as much of `input`/`output`/`params` as you can.

2021-02-18 12:27 UTC, hassanfa commented on BALSAMIC/workflows/balsamic.smk
> +            Path(output[0]).touch()
remove this and bring 

```
       with open(str(output[0]), mode='w') as finish_file:
            finish_file.write('%s\n' % datetime.datetime.now())
```

here

2021-02-18 12:27 UTC, hassanfa commented on BALSAMIC/workflows/balsamic.smk
> -        import datetime
Keep this

2021-08-16 13:44 UTC, ivadym commented
It will be addressed in #707.

2021-08-16 13:44 UTC, closed without merging