Feature/pon config
Clinical-Genomics/BALSAMIC pull request #611
Opened 2021-04-12 14:51 UTC by ashwini06

### This PR:

Creates a pon config json file for panel of normal analysis.

Test Command: 
```
balsamic config pon --case-id securetoad2 -p  /home/proj/production/cancer/reference/target_capture_bed/production/balsamic/gmcksolid_4.1_hg19_design.bed --balsamic-cache /home/proj/long-term-stage/cancer/UMI_analysis_runs_APJ/balsamic_test_cache/ --analysis-dir /home/proj/long-term-stage/cancer/PON_analysis_runs_APJ/PON_test_datasets/ -n /home/proj/long-term-stage/cancer/PON_analysis_runs_APJ/PON_test_datasets/securetoad/fastq/concatenated_ACC6498A8_XXXXXX_R_1.fastq.gz -n /home/proj/long-term-stage/cancer/PON_analysis_runs_APJ/PON_test_datasets/securetoad/fastq/concatenated_ACC6476A3_XXXXXX_R_1.fastq.gz -g hg19 
```

Analysis Screenshot:

<img width="1405" alt="Screenshot 2021-04-12 at 16 36 48" src="https://user-images.githubusercontent.com/6302819/114412351-4d180780-9bad-11eb-95fa-55167fd4ba14.png">

2021-04-19 09:02 UTC, hassanfa requested changes
Some minor comments in .smk file and I think it good to go.

2021-04-19 10:16 UTC, ashwini06 commented on BALSAMIC/commands/config/case.py
> +    	umiworkflow=umiworkflow if panel_bed else False
In PON cli command, we don't have the option for umiworkflow. And in order to reuse the `AnalysisModel` in  `PonBalsamicConfigModel` I moved `umiworkflow` to BalsamicConfigModel.

2021-04-19 10:20 UTC, hassanfa commented on BALSAMIC/commands/config/case.py
> +    	umiworkflow=umiworkflow if panel_bed else False
Makes sense. We need to refactor models as well so they can inherit properly.

2021-04-19 10:50 UTC, ashwini06 commented on BALSAMIC/workflows/PON.smk
> +    input: ALL_REFS + ALL_COVS +  PON_DONE #+ CNV_DONE
Fixed!

2021-05-06 21:30 UTC, hassanfa approved these changes
Very nice work! good to go.

2021-05-07 07:33 UTC, merged