Add Delly somatic SV caller [issue 644 ]
Clinical-Genomics/BALSAMIC pull request #645
Opened 2021-06-03 13:36 UTC by khurrammaqbool

### This PR:

Added:

- Delly somatic SV caller

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-06-03 13:53 UTC, khurrammaqbool commented
Add exclusion list for delly in cache

2021-06-09 07:15 UTC, hassanfa requested changes
Well done!

Some minor comments, a conflict to fix, and also please use longer descriptive names rather than short and abbreviated.

i.e. `dly_excl` --> `delly_exclusion` all over the code.

2021-06-09 07:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +rule delly_tumor_normal:
Please follow the order as described in: https://balsamic.readthedocs.io/en/latest/snakemake_etiquette.html

2021-06-09 07:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        benchmark_dir + 'delly_tumor_normal_' + config["analysis"]["case_id"] + ".delly.tsv"
```suggestion
        benchmark_dir + 'delly_tumor_normal_' + config["analysis"]["case_id"] + "_delly.tsv"
```

2021-06-09 07:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +    threads: get_threads(cluster_config, "delly_tumor_normal")
Please add a descriptive message after this

2021-06-09 07:15 UTC, hassanfa commented on tests/test_data/references/genome/dly_excl.tsv
> +chr1	0	10000	telomere
You should delete the content of the file, and have it as an empty file. This is a fixture and placeholder for tests.

2021-06-09 07:15 UTC, hassanfa commented on tests/test_data/references/reference.json
> +        "dly_excl": "tests/test_data/references/genome/dly_excl.tsv"
```suggestion
        "delly_exclusion": "tests/test_data/references/genome/delly_exclusion.tsv"
```

2021-06-09 07:15 UTC, hassanfa commented on tests/conftest.py
> +            "dly_excl":
```suggestion
            "delly_exclusion":
```

2021-06-09 07:15 UTC, hassanfa commented on tests/conftest.py
> +            "tests/test_data/references/genome/dly_excl.tsv"
```suggestion
            "tests/test_data/references/genome/delly_exclusion.tsv"
```

2021-06-10 09:24 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +    threads: get_threads(cluster_config, "delly_tumor_normal")
Added the message

2021-06-10 09:25 UTC, khurrammaqbool commented on tests/test_data/references/genome/dly_excl.tsv
> +chr1	0	10000	telomere
Now the file is empty.

2021-06-10 10:34 UTC, hassanfa approved these changes
Well done! Some minor changes I made. Merge when tests are done.

2021-06-10 10:34 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +    threads: get_threads(cluster_config, "delly_tumor_normal")
```suggestion
    threads:
        get_threads(cluster_config, "delly_tumor_normal")
```

2021-06-10 10:34 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +    threads: get_threads(cluster_config, "delly_tumor_normal")
new line here as well.

2021-06-10 10:34 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +    threads: get_threads(cluster_config, "manta_tumor_normal")
```suggestion
    threads:
        get_threads(cluster_config, "manta_tumor_normal")
```

2021-06-10 10:34 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +    threads: get_threads(cluster_config, "manta_tumor_normal")
new line

2021-06-10 10:34 UTC, hassanfa commented on CHANGELOG.rst
> +* bcf to vcf command
We can delete this since it is part of the Delly rule's `shell` already.
```suggestion
```

2021-06-10 14:26 UTC, ashwini06 reviewed
Nice job 👍  Few comments from my end

2021-06-10 14:26 UTC, ashwini06 commented on CHANGELOG.rst
> +* Refactor snakemake manta and delly rules according to snakemake etiquette
Changelog reflects the changes we made w.r.t develop/master branches. As delly rule is very recent and I think we don't need to add this to changelog

```suggestion
* Refactor snakemake manta rule according to snakemake etiquette
```

2021-06-15 13:56 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/delly.vcf.gz {output.final};
Fixed

2021-06-15 13:57 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +bcftools view -O z -o {params.tmpdir}/delly.vcf.gz {params.tmpdir}/delly.somatic.bcf
Fixed

2021-06-15 13:58 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +echo -e \"{params.tumor}\\tTUMOR\\n{params.normal}\\tNORMAL\" > {output.namemap};
{params.tmpdir}/samples.tsv is for delly internal filter command and is different from {output.namemap}.

2021-06-15 14:00 UTC, khurrammaqbool commented on BALSAMIC/utils/constants.py
> +            "genome_version": "hg19",
Fixed

2021-06-15 14:07 UTC, khurrammaqbool commented on CHANGELOG.rst
> +* Refactor snakemake manta and delly rules according to snakemake etiquette
fixed

2021-06-15 14:31 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +echo -e \"{params.tumor}\\tTUMOR\\n{params.normal}\\tNORMAL\" > {output.namemap};
Is that delly accepts Normal samples name as only 'control', whereas in balsamic namemap we have given names for NORMAL samples as 'normal'

2021-06-15 14:32 UTC, ashwini06 approved these changes

2021-07-02 12:54 UTC, ashwini06 reviewed
@khurrammaqbool : 2 minor comments

2021-07-02 12:54 UTC, ashwini06 commented on BALSAMIC/workflows/reference.smk
> +sed -i 's/chr//g' {input.delly_exclusion} 2> {log}
Is the output a 3-column bed file? Then why not output to '.txt'/ '.bed' file. Any specific reasons to output results to log file?

2021-07-02 12:54 UTC, ashwini06 commented on CHANGELOG.rst
> +=======
```suggestion
=======
```
This lines indicates the latest additions to changelog (or called conflicts). Resolve them on your local branch and push them.

2021-07-02 13:14 UTC, khurrammaqbool commented on BALSAMIC/workflows/reference.smk
> +sed -i 's/chr//g' {input.delly_exclusion} 2> {log}
The file already has .tsv extension.

2021-07-05 06:44 UTC, hassanfa requested changes
`prepare_delly_exclusion` needs an output. Otherwise, looks like a rogue rule.

2021-07-05 06:44 UTC, hassanfa commented on BALSAMIC/workflows/reference.smk
> +sed -i 's/chr//g' {input.delly_exclusion} 2> {log}
It is not transparent what this rule is doing. It is readable it is replacing the `chr` from a file, but it does not have an output. Looks like a rogue rule. Can you please add an output to it, and then use that output for `rule all`?

2021-07-05 10:19 UTC, khurrammaqbool commented on BALSAMIC/workflows/reference.smk
> +sed -i 's/chr//g' {input.delly_exclusion} 2> {log}
@hassanfa The output file is added

2021-07-05 12:46 UTC, hassanfa approved these changes
💯 awesome! Merge ready 😃

2021-07-05 13:09 UTC, merged