Feat/umi pass vcf
Clinical-Genomics/BALSAMIC pull request #692
Opened 2021-07-20 11:51 UTC by ashwini06

### This PR:
Filter TNScope UMI `pass` variants  
### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-07-20 14:05 UTC, hassanfa requested changes
Some minor changes. Also, in order to deliver this rule, please add the rule name here: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/commands/report/deliver.py#L94

2021-07-20 14:05 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_umi_pass.rule
> +        sample_id = '{case_name}'
Isn't this case_name?
```suggestion
        case_name = '{case_name}'
```

2021-07-20 14:05 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_umi_pass.rule
> +        "Filtering TNscope umi PASS variants using bcftools for {params.sample_id}"
```suggestion
        "Filtering TNscope umi PASS variants using bcftools for {params.case_name}"
```

2021-07-20 14:05 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_umi_pass.rule
> +        vcf_pass = vep_dir + "{var_type}.somatic.{case_name}.TNscope_umi.pass.vcf.gz",
```suggestion
        umi_vcf_pass = vep_dir + "{var_type}.somatic.{case_name}.TNscope_umi.pass.vcf.gz",
```

Changing this to umi_vcf_pass will cause having a `clinical-umi-vcf-pass` in the housekeeper delivery files that we can use to upload to Scout. Otherwise it will collide with `clinical-vcf-pass` in the delivery of `ngs_filter_vardict`

2021-07-20 14:05 UTC, hassanfa commented on CHANGELOG.rst
> +* Filter TNscope umi ``pass`` variants
```suggestion
* Filter TNscope umi ``pass`` variants and add them to final delivery
```

2021-07-21 07:57 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_umi_pass.rule
> +        "Filtering TNscope umi PASS variants using bcftools for {params.sample_id}"
Fixed!

2021-07-21 07:59 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_umi_pass.rule
> +        vcf_pass = vep_dir + "{var_type}.somatic.{case_name}.TNscope_umi.pass.vcf.gz",
Fixed!

2021-07-21 07:59 UTC, ashwini06 commented on CHANGELOG.rst
> +* Filter TNscope umi ``pass`` variants
Fixed!

2021-07-21 08:25 UTC, hassanfa approved these changes
💯

2021-07-21 08:25 UTC, hassanfa commented on BALSAMIC/commands/report/deliver.py
> +	"ngs_filter_tnscope_umi",
is the spacing a bit off here? could you run `yapf -i` on this file and check please?

2021-07-21 08:29 UTC, ashwini06 commented on BALSAMIC/commands/report/deliver.py
> +	"ngs_filter_tnscope_umi",
Now its fixed:)

2021-07-21 08:51 UTC, merged