Feat/ascat rules
Clinical-Genomics/BALSAMIC pull request #695
Opened 2021-07-23 13:39 UTC by khurrammaqbool

### This PR:

(If this is a release PR, no need to add following. Leave this part empty)
(Use the following lines to create a PR text body. Make sure to remove all non-relevant one after you're done)
(Repeat each field as many times as necessary)

Added: ascatngs rules.

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-07-23 13:50 UTC, hassanfa requested changes
Some general comments.

Please paste an screenshot that show ascatngs in the final workflow job names.

2021-07-23 13:50 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        ASPCFplot = vcf_dir + "SV.somatic." + config["analysis"]["case_id"] + ".ascat.ASPCF.png",
lower case please if possible.

2021-07-23 13:50 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        get_threads(cluster_config, "ascat_tumor_normal")
add this to https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/config/cluster.json file

2021-07-23 13:50 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +source activate {params.conda};
There is no need for conda in ascat container

2021-07-23 13:50 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        conda = config["bioinfo_tools"].get("ascat")
there is no need for conda in ascat container.

2021-07-23 13:50 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +ascat.pl -protocol WGS -species human -assembly GRCh37 -cpus 36 -reference {input.fa} -snp_gc {input.gccorrection} -outdir {params.tmpdir} -gender L -locus {input.chryloci} -tumour {input.bamT} -norm
Is it possible to have this as multiline command please?

2021-07-23 13:50 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
> +rule ascat_tumor_only:
similar comment to tumor_normal apply here as well. so I won't repeat them.

2021-07-23 13:50 UTC, hassanfa commented on CHANGELOG.rst
> +* ascat tumor normal and tumor only rules
```suggestion
* ascat tumor normal and tumor only rules to WGS workflow
```

2021-08-16 13:54 UTC, khurrammaqbool commented
Fixed in https://github.com/Clinical-Genomics/BALSAMIC/pull/699

2021-08-16 13:54 UTC, closed without merging