refactor annotation rules according snakemake git etiquette
Clinical-Genomics/BALSAMIC pull request #696
Opened 2021-07-29 12:08 UTC by ashwini06

### This PR:

Refactors annotate snakemake rules according to snakemake git etiquette
Part of issue https://github.com/Clinical-Genomics/BALSAMIC/issues/636

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-07-29 21:04 UTC, khurrammaqbool approved these changes
Some minor changes.

2021-07-29 21:04 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule
> +rule bcftools_filter_vardict_tonly:
same  as commented above. It may be better to write tumor_only.

2021-07-29 21:04 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule
> +rule bcftools_filter_tnscope_tn:
...tumor_normal...

2021-07-29 21:04 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +rule bcftools_filter_tnscope_tonly:
as mentioned above

2021-07-29 21:04 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +rule bcftools_intersect_tonly:
as mentioned above and all related occurrences..

2021-07-30 08:35 UTC, hassanfa approved these changes
😎 cool that you refactored some more.

Besides KM's comments, what about just removing tonly and tn from Rule names? File names already have tn/tonly.

2021-07-30 09:24 UTC, ashwini06 commented
> 😎 cool that you refactored some more.
> 
> Besides KM's comments, what about just removing tonly and tn from Rule names? File names already have tn/tonly.

Thanks for the review during your vacation 😄  Agree with both of your comments. It's a tradeoff, if we wanna have our rule names of shorter length then we can skip it, as filenames describe, or else if rule names need to be precisely clearly then it is good with the addition of `*_tumor_only/*_tumor_normal`.

2021-08-17 12:15 UTC, hassanfa requested changes
Changing name of the rules for this step will cause some a delivery problem. Please crosscheck with https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/commands/report/deliver.py#L94 if new rules are matching them or not.

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/rankscore.rule
> +rule genmod_rankscore_vardict:
```suggestion
rule genmod_score_vardict:
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/rankscore.rule
> +    message_text = "{var_type}.somatic.{case_name}.vardict.all.filtered.pass.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/rankscore.rule
> +    "and compress vcf using bcftools on {params.message_text}")
```suggestion
    "and compress vcf using bcftools")
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule
> +    message_text = "{var_type}.somatic.{case_name}.vardict.all.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule
> +    "Filtering vardict tumor-normal annotated variants using bcftools on {params.message_text}"
```suggestion
    "Filtering vardict tumor-normal annotated variants using bcftools"
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule
> +    message_text=  "{var_type}.somatic.{case_name}.vardict.all.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_only.rule
> +    "Filtering vardict tumor-only annotated variants using bcftools on {params.message_text}"
```suggestion
    "Filtering vardict tumor-only annotated variants using bcftools."
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_sv_filter.rule
> +    message_text = "{var_type}.somatic.{case_name}.manta.all.vcf.gz",
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_sv_filter.rule
> +    ("Filtering manta annotated structural variants using bcftools on {params.message_text}")
```suggestion
    "Filtering manta annotated structural variants using bcftools."
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule
> +    message_text = "{var_type}.somatic.{case_name}.tnscope.all.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_normal.rule
> +    "Filtering wgs tumor-normal tnscope annotated variants using bcftools on {params.message_text}"
```suggestion
    "Filtering wgs tumor-normal tnscope annotated variants using bcftools."
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    message_text = "{var_type}.somatic.{case_name}.tnscope.all.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    "Filtering wgs tumor-only tnscope annotated variants using bcftools on {params.message_text}"
```suggestion
    "Filtering wgs tumor-only tnscope annotated variants using bcftools."
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    message_text = "{var_type}.somatic.{case_name}.tnhaplotyper.all.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    "Filtering wgs tumor-only tnhaplotyper annotated variants using bcftools on {params.message_text}"
```suggestion
    "Filtering wgs tumor-only tnhaplotyper annotated variants using bcftools."
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    message_text = "{var_type}.somatic.{case_name}.tnscope_isec.filtered.vcf.gz"
```suggestion
```

2021-08-17 12:15 UTC, hassanfa commented on BALSAMIC/snakemake_rules/annotation/varcaller_wgs_filter_tumor_only.rule
> +    "Retrieving common annotated variants between tnscope and tnhaplotyper using bcftools for {params.message_text}"
```suggestion
    "Retrieving common annotated variants between tnscope and tnhaplotyper using bcftools."
```

2021-08-17 15:12 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/rankscore.rule
> +rule genmod_rankscore_vardict:
Fixed!

2021-08-18 08:55 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/rankscore.rule
> +    message_text = "{var_type}.somatic.{case_name}.vardict.all.filtered.pass.vcf.gz"
`message_text` replaced with `case_name`

2021-08-18 08:55 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_filter_tumor_normal.rule
> +    message_text = "{var_type}.somatic.{case_name}.vardict.all.vcf.gz"
Fixed!

2021-08-19 13:00 UTC, hassanfa approved these changes
👍🏽 A conflict and merge is a go!

2021-08-20 11:42 UTC, khurrammaqbool commented on CHANGELOG.rst
> +* Refactor snakemake annotate rules according to snakemake etiquette #636
Suggestion: Refactor ```snakemake``` ```annotate``` rules according to snakemake etiquette #636
It would be nice to make all highlights consistent across the document.

2021-08-20 11:42 UTC, khurrammaqbool commented on BALSAMIC/commands/report/deliver.py
> +        "bcftools_filter_vardict_tumor_normal",
tumor_only & tumor_normal 
--OR--
tumoronly & tumornormal

2021-08-20 12:02 UTC, ashwini06 commented on BALSAMIC/commands/report/deliver.py
> +        "bcftools_filter_vardict_tumor_normal",
Good catch, changed everything to `tumor_only`

2021-08-20 12:02 UTC, ashwini06 commented on CHANGELOG.rst
> +* Refactor snakemake annotate rules according to snakemake etiquette #636
Fixed!

2021-08-20 12:25 UTC, merged