Fix/delly run
Clinical-Genomics/BALSAMIC pull request #698
Opened 2021-07-29 19:47 UTC by khurrammaqbool

### This PR:

Fixed: Delly run.

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-07-30 08:26 UTC, hassanfa requested changes
Looks like you already managed to fix it, but you don't need to add it separately. Either make it so that vep rule can pick it up or add it to the line i commented.

All the snv and sv somatic is annotated here: https://github.com/Clinical-Genomics/BALSAMIC/blob/9ed348a37893b375ff367aa5498eb212a37424ef/BALSAMIC/workflows/balsamic.smk#L334 irregardless of their source as long as they are in the model.

2021-07-30 08:26 UTC, hassanfa commented on BALSAMIC/workflows/balsamic.smk
> +# delly get vcf file
This is not needed if you have added it to the models.

In order to have another file produced then you should simply add delly here

https://github.com/Clinical-Genomics/BALSAMIC/blob/9ed348a37893b375ff367aa5498eb212a37424ef/BALSAMIC/workflows/balsamic.smk#L362

2021-07-30 08:54 UTC, ashwini06 reviewed
👍  Few comments and after fixing these changes, can you also paste a screenshot of balsamic dry-run mode to see the effective changes

2021-07-30 08:54 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +echo -e \"{params.tumor}\\ttumor\\n{params.normal}\\tcontrol\" > {params.tmpdir}/samples.tsv;
```suggestion
echo -e \"{params.tumor}\\tTUMOR\\n{params.normal}\\tNORMAL\" > {params.tmpdir}/samples.tsv;
```

2021-07-30 08:54 UTC, ashwini06 commented on BALSAMIC/utils/models.py
> +#    delly: VarcallerAttribute
```suggestion
    delly: VarcallerAttribute
```

2021-07-30 08:54 UTC, ashwini06 commented on BALSAMIC/workflows/balsamic.smk
> +analysis_specific_results.extend([Path(vcf_dir + "SV.somatic." + config["analysis"]["case_id"] + ".delly.vcf.gz")])
Can you add the `vep` annotated `delly` vcf as the final analysis output? And you can combine this with line 363. As we discussed, try using `get_vcf` for obtaining the delly annotated vcf file.

2021-07-30 09:03 UTC, khurrammaqbool commented on BALSAMIC/workflows/balsamic.smk
> +analysis_specific_results.extend([Path(vcf_dir + "SV.somatic." + config["analysis"]["case_id"] + ".delly.vcf.gz")])
I have tried, but get_vcf on delly fails.

2021-07-30 09:05 UTC, khurrammaqbool commented on BALSAMIC/utils/models.py
> +#    delly: VarcallerAttribute
I have commented it because it failed py.test and I could not figure out from the log. Any suggestion on it.

2021-07-30 09:07 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +echo -e \"{params.tumor}\\ttumor\\n{params.normal}\\tcontrol\" > {params.tmpdir}/samples.tsv;
sample.tsv is not same as namemap, so we generate both files.

2021-07-30 10:13 UTC, ashwini06 commented on BALSAMIC/workflows/balsamic.smk
> +analysis_specific_results.extend([expand(vcf_dir + "{vcf}.vcf.gz",
You are close enough, but we need annotated delly vcf as file output. I suggest the following

```
analysis_specific_results.extend([expand(vep_dir + "{vcf}.all.filtered.pass.vcf.gz",
                                        vcf=get_vcf(config, ["manta", "delly"], [config["analysis"]["case_id"]]))])
```

But this won't work unless you fix your delly output vcf filename. Take a close on the pattern of your delly rule vcf output and vep input filename and change accordingly. https://github.com/Clinical-Genomics/BALSAMIC/blob/81668fa5aae9fe81c63c637d0b2282546074daa6/BALSAMIC/snakemake_rules/annotation/vep.rule#L7

2021-07-30 10:14 UTC, ashwini06 reviewed
Please check my above comment

2021-07-30 10:27 UTC, khurrammaqbool commented
<img width="534" alt="Screenshot 2021-07-30 at 10 53 01" src="https://user-images.githubusercontent.com/5569347/127639988-fc3ee079-b227-442f-a0d2-189963fa6928.png">
<img width="521" alt="Screenshot 2021-07-30 at 10 54 51" src="https://user-images.githubusercontent.com/5569347/127640057-9f0d68f3-197d-48fb-ae4f-02547c3fbdcc.png">

2021-07-30 10:31 UTC, khurrammaqbool commented on BALSAMIC/workflows/balsamic.smk
> +# delly get vcf file
Thanks! It is fixed now.

2021-07-30 11:40 UTC, khurrammaqbool commented on BALSAMIC/workflows/balsamic.smk
> +analysis_specific_results.extend([expand(vcf_dir + "{vcf}.vcf.gz",
It is now fixed.

2021-08-02 10:10 UTC, ashwini06 approved these changes
It's good to go 👍  
**Optional** : A small suggestion could be in snakemake delly rules, if params are described in long format rather than short-form, (`eg: -f/--filter`), the quality of code will be enhanced for readability.

2021-08-02 10:49 UTC, merged