Refactor/umi variantcalling snakemake rules
Clinical-Genomics/BALSAMIC pull request #701
Opened 2021-08-06 16:22 UTC by ashwini06

### This PR:

Refactor UMI and variant calling snakemake rules.
Part of https://github.com/Clinical-Genomics/BALSAMIC/issues/636

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-08-11 07:42 UTC, khurrammaqbool approved these changes

2021-08-11 07:42 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +        "Calling SNVs and SVs using Sentieon TNscope and applying ML algorithm for sample {params.case_name}"
ML may mean machine learning or maximum likelihood. It may be better to expand it.

2021-08-11 11:49 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +        "Calling SNVs and SVs using Sentieon TNscope and applying ML algorithm for sample {params.case_name}"
changed to its full form machine learning 👍

2021-08-17 11:19 UTC, hassanfa requested changes
meticulous and well done! Some testing required regarding Sentieon syntax changes.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
>  -q {input.recal_data_table} \
Will this work? some of the options are unique to driver and some are unique to algo.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
>  -q {input.recal_data_table} \
From the help menu I see the following: 
![image](https://user-images.githubusercontent.com/1086877/129716203-a24bc69f-624b-43d0-b80d-c74f83694f08.png)

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
> +        sample_id =  config["analysis"]["case_id"]
```suggestion
        sample =  config["analysis"]["case_id"]
```

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
> +        "Calling SNVs using sentieon TNscope for sample {params.sample_id}"
```suggestion
        "Calling SNVs using sentieon TNscope for sample {params.sample}"
```

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
> +{params.sentieon_exec} driver --algo TNscope \
same previous one. I'm not sure this will work. Requires testing.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +{params.sentieon_exec} driver --algo QualCal \
same as previous two. `--algo QualCal` might not work.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +{params.sentieon_exec} driver --algo QualCal \
This one as well. --algo QualCal might not work with options after. Better test it.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +{params.sentieon_exec} driver --algo QualCal \
Here as well.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +        ""
message string is empty.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +{params.sentieon_exec} driver --algo Realigner \
same --algo  comment as previous ones.

2021-08-17 11:19 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +{params.sentieon_exec} driver --algo TNhaplotyper \
I guess I'll stop here about algo, but similar to all the previous ones.

2021-08-17 12:26 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
> +        sample_id =  config["analysis"]["case_id"]
maybe changing to `case_name` would be appropriate here?

2021-08-17 13:26 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
> +        sample_id =  config["analysis"]["case_id"]
Sure thing! makes sense.

2021-08-17 14:09 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/umi/generate_AF_tables.rule
>          get_threads(cluster_config, "bcftools_query_generatebackgroundaf_umitable")
Fixed!

2021-08-17 14:10 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/germline.rule
> +        sample_id = '{sample_type}'
Fixed!

2021-08-17 15:04 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
>  -q {input.recal_data_table} \
You are right. Sentieon follows this order of `driver_options` followed by `algo_options`. Interchanging or random placing of args does not work. For example: Displays error as such `TNhaplotyper: invalid option -- 'r'
TNhaplotyper: unknown option`. 

I fixed the order correctly now!

2021-08-17 15:05 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
> +        ""
Fixed!

2021-08-19 13:07 UTC, hassanfa approved these changes
💯 Merge it! 😄

2021-08-20 10:54 UTC, merged