feat: save a JSON file of QC metrics
Clinical-Genomics/BALSAMIC pull request #723
Opened 2021-08-26 15:32 UTC by ivadym

### This PR:

Creates a QC pydantic model and dumps the summarised metrics into a JSON file. The previous QC workflow has not been deleted.

Added:

Pydantic models that shape the QC metrics JSON generation.
qc_metrics_summary.json is saved in the analysis output directory.

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-09-07 09:02 UTC, ashwini06 reviewed
Well done 🥇 nice implementation! 

Two points, I am thinking related to PR is : 
1) having two similar functions `get_qc_metrics` and `get_qc_metrics_json`. Can we merge this into one and use the latest  `get_qc_metrics_json` in https://github.com/Clinical-Genomics/BALSAMIC/blob/37a1f86aaa5120c6f1b5196c5e97952ddd867b12/BALSAMIC/commands/report/deliver.py#L175 as well?  - @hassanfa 

2) Is this PR only about retrieving metrics or also checking if the qc metrics is passed/failed?
according to our defined thresholds like here: https://github.com/Clinical-Genomics/BALSAMIC/blob/05646bc2f94b1c17eb571489f444f4250e929217/BALSAMIC/utils/constants.py#L131

2021-09-07 09:48 UTC, ivadym commented
Thanks for your comments @ashwini06! 

1. Yes, these two functions should be merged. I was planning to do that in another PR (along with some more changes to deliver), but maybe it's better to directly remove `get_qc_metrics()` here, so I will do that.

2. And this PR is only about retrieving metrics and saving them to analysis/qc. The validation part will be addressed in another PR and the `qc_check()` workflow removed.

2021-09-07 10:01 UTC, ashwini06 commented
> Thanks for your comments @ashwini06!
> 
> 1. Yes, these two functions should be merged. I was planning to do that in another PR (along with some more changes to deliver), but maybe it's better to directly remove `get_qc_metrics()` here, so I will do that.
> 2. And this PR is only about retrieving metrics and saving them to analysis/qc. The validation part will be addressed in another PR and the `qc_check()` workflow removed.

Good, these points are already considered. Then it's better we can merge this PR and take these points as new issues.

2021-09-07 10:04 UTC, ashwini06 commented
> Kudos, SonarCloud Quality Gate passed!    ![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=BUG)
> [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=VULNERABILITY)
> [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=SECURITY_HOTSPOT)
> [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=Clinical-Genomics_BALSAMIC&pullRequest=723&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=Clinical-Genomics_BALSAMIC&pullRequest=723) No Coverage information
> [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=Clinical-Genomics_BALSAMIC&pullRequest=723&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Clinical-Genomics_BALSAMIC&pullRequest=723&metric=new_duplicated_lines_density&view=list)

@ivadym: Sonarcloud complains about code smell; check if you can reduce the complexity of long `for loop` by splitting some lines into functions, if not possible we can ignore it.

2021-09-07 14:45 UTC, hassanfa requested changes
Minor comment on the validator.

Great work ⭐

2021-09-07 14:45 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +    sequencing_type: List[str]
Please add a validator for this. Something like:

```python
    @validator("sequencing_type", check_fields=False)
    def sequencing_type_literal(cls, value) -> str:
        "Validate sequencing type"
        assert set(value).issubset(
            set(SEQUENCING_TYPE)
        ), f"{value} is not not a valid sequencing type."
        return value
```

2021-09-07 14:45 UTC, hassanfa commented on BALSAMIC/utils/qc_metrics.py
>  MULTIPLE_JSON = [
agreed, this part can be removed in this PR.

2021-09-07 14:45 UTC, hassanfa commented on BALSAMIC/utils/models.py
> +class QCCheckModel(BaseModel):
Not to be picky, but this doesn't really check it, does it? Mostly it is about its name. It should reflect what it is doing.

My suggestions would be something like: QCExtractionModel

2021-09-07 14:45 UTC, hassanfa commented on tests/utils/test_models.py
> +
Looks like there are some fixtures here. You should create them in `tests/utils/` and move them there. If it is too much work, you can ignore this comment.

2021-09-08 13:03 UTC, ivadym commented
Updated Dockerfile & container pushed to [clinicalgenomics/balsamic:develop-balsamic_container](https://hub.docker.com/layers/clinicalgenomics/balsamic/develop-balsamic_container/images/sha256-a58a875b2398365d4bd4de99d367785c199275ff72b8deb0cf8d55808095a8f6?context=repo).

2021-09-09 13:32 UTC, ivadym commented on BALSAMIC/utils/qc_metrics.py
>  MULTIPLE_JSON = [
Addressed in 03b2457. I removed that part and updated `deliver.py` and `qc_report.py` to behave the same way (although they'll be changed in the future I suppose).

2021-09-09 13:34 UTC, ivadym commented on BALSAMIC/utils/rule.py
> +    output: sequencing type string]
Typo corrected in 6ec51db.

2021-09-09 13:36 UTC, ivadym commented on BALSAMIC/utils/models.py
> +    sequencing_type: List[str]
Added in the 3ce688c commit.

2021-09-09 13:39 UTC, ivadym commented on BALSAMIC/utils/models.py
> +class QCCheckModel(BaseModel):
Changed in 6ec51db.

2021-09-09 13:45 UTC, ivadym commented on tests/utils/test_models.py
> +
I moved it to `tests/conftest.py` , which already has some fixtures defined if that's ok. Adressed in 3ce688c.

2021-09-10 13:30 UTC, hassanfa approved these changes
Well done. ready to merge!

2021-09-14 08:41 UTC, ivadym commented
Solved misbehaviour after force-pushing to feat/QC_check branch. New PR: #754.

2021-09-14 08:41 UTC, closed without merging