Changed: store pon reference
Clinical-Genomics/BALSAMIC pull request #736
Opened 2021-09-01 07:11 UTC by ashwini06

### This PR:

Changed:

PON references can be stored in the same location where production panel bed files are located. Related to https://github.com/Clinical-Genomics/cgp-cancer-cnvcall/issues/10

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-09-01 10:54 UTC, hassanfa approved these changes
👍🏽 

Not that it is important, but I recommend to have constants upper case, and variables lower case. If ALL_* variables are indeed constants, keep them upper otherwise all of them should be lowercase. you make the call.

2021-09-01 13:04 UTC, ashwini06 commented
@hassanfa : No this doesnt work , no permissions to write to this path `home/proj/production/cancer/reference/target_capture_bed/production/balsamic/PON_references`
<img width="1411" alt="Screenshot 2021-09-01 at 15 02 55" src="https://user-images.githubusercontent.com/6302819/131675804-b67cd5c2-32ce-4825-a1b0-086fcb04fa2a.png">

2021-09-02 06:56 UTC, hassanfa requested changes

2021-09-02 06:56 UTC, hassanfa commented on BALSAMIC/workflows/PON.smk
> +pon_dir = panel_ref_dir + "/" + "PON_references" + "/"
I commented on PR. These lines have to be changed. Can we use `--analysis-dir` functionality here? The same way that a result_dir is defined in main workflow, result_dir is used to store results.

2021-09-02 07:16 UTC, ashwini06 commented on BALSAMIC/workflows/PON.smk
> +pon_dir = panel_ref_dir + "/" + "PON_references" + "/"
@hassanfa: Previously, it was writing to the `result_dir` in `cnv` folder. Please see lines 25, 43-44 in this script.

2021-09-02 07:18 UTC, ashwini06 commented
> @ashwini06 this should not write in the the same path that we are using for panel of normals. It should write the CNN to a user defined path. And then user can decide what to do with it. Is it possible to change the behavior as such?

But isn't we decided to store all PON references in a commonplace? Related to Clinical-Genomics/cgp-cancer-cnvcall#10

2021-09-02 08:05 UTC, hassanfa commented
We discussed it, of course. Probably I didn't describe the solution properly, that is to generate a `*cnn` file then add it to the repository via a pull request and not directly on Hasta.

Does that make sense? This way, we can control what and which capture bed is going to have a panel of normal.

2021-09-02 11:20 UTC, ashwini06 commented
> We discussed it, of course. Probably I didn't describe the solution properly, that is to generate a `*cnn` file then add it to the repository via a pull request and not directly on Hasta.
> 
> Does that make sense? This way, we can control what and which capture bed is going to have a panel of normal.

@hassanfa : Maybe, earlier I also didn't capture your message correctly :innocent: OK now this is clear. So, the previous implementation in the PON workflow is doing the right thing of storing PON reference `.cnn` file in the results_dir. Now i won't change its storage location, instead in this PR, I will add the panel name to the generated PON reference file. Previously it was just called as `cnv_dir + config["analysis"]["case_id"] + "_PON_reference.cnn"`. New change will be like `cnv_dir + panel_name + "_" + config["analysis"]["case_id"] + "_PON_reference.cnn"`. This will give better idea, from which panel and case_id, the PON_reference.cnn is generated from.

<img width="475" alt="aaa" src="https://user-images.githubusercontent.com/6302819/131834370-0934255f-0c7f-408d-b365-c02ff7ef82ad.png">

2021-09-03 13:16 UTC, merged