feat: ascatNgs PDF delivery
Clinical-Genomics/BALSAMIC pull request #828
Opened 2021-11-30 16:08 UTC by ivadym

### This PR:

Adds a new delivery file in BALSAMIC(`PDF`) containing the main `ascatNgs` output plots as well as a table with some sample statistics.

#### Steps

- [x] Merge the `.png` plots and the statistics `.txt` file into a single `PDF`.
- [ ] Create a new snakemake rule to save the generated PDF.

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2021-11-30 16:19 UTC, ivadym commented
Currently generated PDF: 

[ascat.output.pdf](https://github.com/Clinical-Genomics/BALSAMIC/files/7627167/ascat.output.pdf)

@ashwini06 @khurrammaqbool

2021-12-03 14:30 UTC, hassanfa reviewed
Some comments from my side.

2021-12-03 14:30 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +rule ascat_tumor_normal_merge_output:
This rule is going to be submitted by default value of resources. Although it'll take a very short time. Either add it as part of `rule all` and tag it separately, or add rule name to https://github.com/Clinical-Genomics/BALSAMIC/blob/v8.2.3/BALSAMIC/config/cluster.json

2021-12-03 14:30 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        sunrise_plot = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.sunrise.png"
You should consider crunching all these into one:
```suggestion
        sample_statistics = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.samplestatistics.txt",
        ascat_plots = expand(vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + "{output_suffix}", [ ".ascat.ascatprofile.png",".ascat.rawprofile.png" ...])`
```

2021-12-03 14:30 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +            ]
```suggestion
input.ascat_plots
```

2021-12-03 14:30 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        ascat_output_pdf = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.output.pdf"
In this output properly part of https://github.com/Clinical-Genomics/BALSAMIC/blob/595caae47f5198620c963f07275c95ba914b56d0/BALSAMIC/workflows/balsamic.smk#L317 ?

2021-12-03 14:30 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +            output.ascat_output_pdf,
Possible to make this an standalone script have it as `shell` so we can run it within BALSAMIC container instead?

2021-12-03 15:15 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        sunrise_plot = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.sunrise.png"
even more generalization..
`ascat_plots = expand(vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat." + "{output_suffix}" + ".png",  output_suffix=[ "ascatprofile", "rawprofile", "ASPCF", ...])`

2021-12-03 15:18 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        ascat_output_pdf = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.output.pdf"
@ivadym : you should add this output file to analysis_specific_results in balsamic.smk

2021-12-03 15:19 UTC, ashwini06 reviewed
Nice implementation @ivadym 👍🏼

2021-12-05 21:43 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +            output.ascat_output_pdf,
If you mean to run it inside `/balsamic_cache/X.X.X/containers/balsamic.sif`, I think we can address it on another PR (currently it is not downloaded when the balsamic cache is generated. I believe that we have not included it within the VALID_CONTAINER_CONDA_NAME constant).

2021-12-05 22:32 UTC, ivadym reviewed
Thank you for your comments and time @hassanfa and @ashwini06. I followed your suggestions but feel free to add any comments you consider appropriate.

Job rules that are run in balsamic dry-mode @ashwini06:

<img width="734" alt="Screen Shot 2021-12-05 at 23 53 22" src="https://user-images.githubusercontent.com/26309194/144767179-b788f843-f008-43b5-9082-71d30a0df14c.png">

Output PDF:

[CNV.somatic.TN_WGS.ascat.output.pdf](https://github.com/Clinical-Genomics/BALSAMIC/files/7659367/CNV.somatic.TN_WGS.ascat.output.pdf)

2021-12-05 22:32 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
I have tried to generalise this part as well but I am not sure how to do it as the path is determined from the parameters and not from wildcards.

2021-12-06 08:53 UTC, ashwini06 requested changes

2021-12-06 08:53 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.germline.png {output.ascat_plots[0]};
```suggestion
cp {params.tmpdir}/{params.tumor}.germline.png {output.ascat_plots[4]};
```

2021-12-06 08:53 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.sunrise.png {output.ascat_plots[2]};
```suggestion
cp {params.tmpdir}/{params.tumor}.sunrise.png {output.ascat_plots[5]};
```

2021-12-06 08:53 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASCATprofile.png {output.ascat_plots[4]};
```suggestion
cp {params.tmpdir}/{params.tumor}.ASCATprofile.png {output.ascat_plots[0]};
```

2021-12-06 08:53 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
```suggestion
cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[2]};
```

2021-12-06 08:53 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
Capturing the output files from the list is fine. But just make sure you have the correct order of filenames

2021-12-06 08:58 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.germline.png {output.ascat_plots[0]};
I updated this in a previous PR (6aca948) this morning.

2021-12-06 09:00 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
I updated this in a previous PR (6aca948) this morning.

2021-12-06 09:01 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
So all the PNG files from tmpdir are copied to output, right? Will a solution like this work? `cp {params.tmp_dir}/*.png {params.output_dir}`

2021-12-06 10:28 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +            output.ascat_output_pdf,
fair enough 👍🏽

2021-12-06 10:33 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
True. All input are TUMOR.XXXX.png. So the string `TUMOR` needs to be replaced by `CNV.somatic.{params.case_name}.ascat`. For future reference something like would work:

```bash
find {params.tmpdir} -name "*.png" \
| while read filename; \
do new_name=$(echo "${{CNV.somatic.{params.case_name}.ascat/{params.tumor}/"$secondString"}}");\
cp "$filename" "$new_name";
done
```

2021-12-06 10:34 UTC, hassanfa commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
It's ugly though 😛

2021-12-06 10:44 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
Beautiful in it's own way*

Maybe it's better to have a snakemake based solution for this, though I couldn’t find anything

2021-12-06 11:01 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +cp {params.tmpdir}/{params.tumor}.ASPCF.png {output.ascat_plots[5]};
We can skip the png outputs and report/deliver only one pdf as it includes all the information, unless we would like to parse the text file for scout etc.

2021-12-06 13:44 UTC, ashwini06 approved these changes

2021-12-06 16:11 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        merge_ascat_output_script= get_script_path("merge_ascat_output.py"),
I agree 😄

2021-12-06 20:48 UTC, ashwini06 approved these changes
💯

2021-12-07 08:01 UTC, merged