feat: add qc only workflow
Clinical-Genomics/BALSAMIC pull request #847
Opened 2022-01-13 13:09 UTC by rannick

Added: qc only workflow

### Review and tests: 
- [x] Tests pass
- [ ] Code review
- [x] New code is executed and covered by tests, and test approve

2022-01-13 15:04 UTC, ashwini06 commented
@rannick Let's discuss this PR tomorrow before I start adding lots of comments 😄

2022-04-01 14:09 UTC, ashwini06 commented on BALSAMIC/workflows/QC.smk
> +        wildcard_dict.update({"bedchrom": config["panel"]["chrom"] if "panel" in config else [],
might not be used by any qc rules.. please cross-check

2022-04-01 14:13 UTC, ashwini06 commented on BALSAMIC/workflows/QC.smk
> +    capture_kit = os.path.split(config["panel"]["capture_kit"])[1]
```suggestion

```
I don't think we need this  capture_kit info to run any qc rules

2022-04-01 14:31 UTC, ashwini06 commented
@rannick any information about which bedfile will be used for running dog genomes? Is canfam3 is the genome build requested by the customer?

2022-04-01 15:05 UTC, rannick commented on .github/workflows/black_linter.yml
> +          version: "22.3.0"
Addressed in 7813839

2022-04-01 15:21 UTC, rannick commented on BALSAMIC/workflows/QC.smk
> +from BALSAMIC.constants.workflow_params import WORKFLOW_PARAMS
https://github.com/Clinical-Genomics/BALSAMIC/blob/7813839207f46b2c06e4ed8d87edbc504fca6a9d/BALSAMIC/snakemake_rules/align/bwa_mem.rule#L20

2022-04-01 15:25 UTC, rannick commented on BALSAMIC/workflows/QC.smk
> +    germline_call_samples.append("normal")
Indeed not needed; addressed in f9c3800

2022-04-04 09:12 UTC, rannick commented on BALSAMIC/commands/config/qc.py
> +)
Actually, multiqc needs a umiworkflow parameter: https://github.com/Clinical-Genomics/BALSAMIC/blob/8914b315ba8cf4486871a46707801dccc648bc71/BALSAMIC/snakemake_rules/quality_control/multiqc.rule#L59

2022-04-04 11:30 UTC, rannick commented on BALSAMIC/commands/config/qc.py
> +)
Set to False

2022-04-04 12:21 UTC, rannick commented on BALSAMIC/workflows/QC.smk
> +        wildcard_dict.update({"bedchrom": config["panel"]["chrom"] if "panel" in config else [],
Not used for qc rules

2022-04-04 12:23 UTC, rannick commented on BALSAMIC/workflows/QC.smk
> +    capture_kit = os.path.split(config["panel"]["capture_kit"])[1]
capture_kit is used in mosdepth and multiqc

2022-04-04 12:25 UTC, rannick commented
canine_exome_16.1 will be the bed file

2022-04-04 12:43 UTC, rannick commented on BALSAMIC/commands/config/qc.py
> +)
We will need

2022-04-05 07:19 UTC, ashwini06 reviewed
Now the only thing I am wondering is that qc_only workflow will be panel specific, as the `config qc` command line requires a mandatory panel-bed option. Thinking, if we can modify slightly the `rules_to_include` in qc.smk to work along with wgs cases as well.

2022-04-06 07:20 UTC, ashwini06 requested changes
@rannick : `qc` is not changed `qc_panel` in some places of code. Can you cross check once again please.

2022-04-06 07:20 UTC, ashwini06 commented on BALSAMIC/utils/models.py
> +            qc : QC analysis only
```suggestion
            qc_panel : QC analysis only
```

2022-04-06 07:20 UTC, ashwini06 commented on BALSAMIC/workflows/QC.smk
> +            qc_metrics_summary = get_qc_metrics_json(params.result_dir, params.sequencing_type, params.panel_bed)
```suggestion
            qc_metrics_summary = get_qc_metrics_json(params.result_dir, params.sequencing_type, params.panel_bed)
```
We don't know any qc check criteria for dog exome panel, we might need to add the dog panel here https://github.com/Clinical-Genomics/BALSAMIC/blob/454c0c450d37c4b73b55e0daf0ff3ed102ef919d/BALSAMIC/constants/quality_check_reporting.py#L53. @ivadym Any inputs here on how to handle qc metrics here?

2022-04-06 14:13 UTC, rannick commented on BALSAMIC/commands/config/qc.py
> +    short_help="Create a sample config file from input sample data for QC analysis",
in [70182b2](https://github.com/Clinical-Genomics/BALSAMIC/pull/847/commits/70182b2a404159d1537b309dbc9fdbbac064f53f)

2022-04-06 14:13 UTC, rannick commented on BALSAMIC/commands/config/qc.py
> +        "For WGS cases, UMI is always disabled."
in [70182b2](https://github.com/Clinical-Genomics/BALSAMIC/pull/847/commits/70182b2a404159d1537b309dbc9fdbbac064f53f)

2022-04-06 14:14 UTC, rannick commented on BALSAMIC/utils/cli.py
> +    if "qc" in analysis_type:
in [70182b2](https://github.com/Clinical-Genomics/BALSAMIC/pull/847/commits/70182b2a404159d1537b309dbc9fdbbac064f53f)

2022-04-06 14:14 UTC, rannick commented on BALSAMIC/utils/models.py
> +            When analysis_type is set to any value other than [single, paired, pon, qc]
in [70182b2](https://github.com/Clinical-Genomics/BALSAMIC/pull/847/commits/70182b2a404159d1537b309dbc9fdbbac064f53f)

2022-04-11 13:30 UTC, rannick commented on BALSAMIC/utils/models.py
> +            qc : QC analysis only
resolved in [70182b2](https://github.com/Clinical-Genomics/BALSAMIC/pull/847/commits/70182b2a404159d1537b309dbc9fdbbac064f53f)

2022-04-11 13:34 UTC, rannick commented on BALSAMIC/workflows/QC.smk
> +            qc_metrics_summary = get_qc_metrics_json(params.result_dir, params.sequencing_type, params.panel_bed)
Updated qc metrics in [97a8738](https://github.com/Clinical-Genomics/BALSAMIC/pull/847/commits/97a8738dc8b58091631367e210ae508d89b2c321). Defaults thresholds for targeted qc metrics are used

2022-04-19 14:36 UTC, ashwini06 approved these changes
Great job 🎆  With successful test runs,  this PR is ready to merge 👍🏼

2022-04-20 08:35 UTC, rannick commented
Test results available in /home/proj/development/cancer/canfam3_testruns/small

2022-04-20 08:36 UTC, merged