feat: add docker container for vcf2cytosure
Clinical-Genomics/BALSAMIC pull request #869
Opened 2022-02-24 14:54 UTC by ashwini06

### This PR:

Added: Docker container for vcf2cytosure. Related to #858 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-03-02 19:31 UTC, ivadym requested changes
👍 

Regarding your comment, it seems that Python does not know where to look for the required modules, but it should be solved setting explicitly the `PYTHONPATH` environment variable. I tested it locally with the changes that I suggested and it works:

<img width="1863" alt="Screen Shot 2022-03-02 at 20 26 40" src="https://user-images.githubusercontent.com/26309194/156435239-694445ee-d67b-4972-b50e-6b85373cf82d.png">

2022-03-02 19:31 UTC, ivadym commented on BALSAMIC/containers/vcf2cytosure/Dockerfile
> +    && pip install -e .
```suggestion
    && cd /opt/${CONTAINER_NAME} \ \
    && pip install --no-cache-dir .
```

2022-03-02 19:31 UTC, ivadym commented on BALSAMIC/containers/vcf2cytosure/Dockerfile
> +ENV PATH="/opt/vcf2cytosure/bin:${PATH}"
```suggestion
ARG CONTAINER_NAME
ENV PATH="/opt/${CONTAINER_NAME}/bin:${PATH}"
ENV PYTHONPATH="/opt/${CONTAINER_NAME}"
```

2022-03-04 13:06 UTC, ashwini06 commented
> 👍
> 
> Regarding your comment, it seems that Python does not know where to look for the required modules, but it should be solved setting explicitly the `PYTHONPATH` environment variable. I tested it locally with the changes that I suggested and it works:
> 
> <img alt="Screen Shot 2022-03-02 at 20 26 40" width="1863" src="https://user-images.githubusercontent.com/26309194/156435239-694445ee-d67b-4972-b50e-6b85373cf82d.png">

Thanks @ivadym for your suggestions :) It works fine now with your suggestions

2022-03-04 13:06 UTC, ashwini06 commented on BALSAMIC/containers/vcf2cytosure/Dockerfile
> +ENV PATH="/opt/vcf2cytosure/bin:${PATH}"
Fixed!

2022-03-04 13:06 UTC, ashwini06 commented on BALSAMIC/containers/vcf2cytosure/Dockerfile
> +    && pip install -e .
FixeD!

2022-03-04 14:27 UTC, ashwini06 commented
@ivadym @khurrammaqbool : Ready for review :speaker:

2022-03-07 08:05 UTC, ivadym approved these changes
👍

2022-03-07 10:37 UTC, merged