Feat/add svdb workflow
Clinical-Genomics/BALSAMIC pull request #873
Opened 2022-03-04 14:10 UTC by khurrammaqbool

### This PR:

Added: SVDB to the workflow

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-03-04 14:17 UTC, khurrammaqbool commented
<img width="773" alt="Screenshot 2022-03-04 at 15 04 23" src="https://user-images.githubusercontent.com/5569347/156778827-f3287fa3-605c-40a4-b4a8-35d1d0980634.png">

<img width="912" alt="Screenshot 2022-03-04 at 15 08 45" src="https://user-images.githubusercontent.com/5569347/156778955-c17b3d43-51cf-47d5-b7e5-88372685099e.png">

<img width="1017" alt="Screenshot 2022-03-04 at 15 09 09" src="https://user-images.githubusercontent.com/5569347/156779048-dba9d888-68c7-4d79-a0d7-4ac3fa8d8338.png">

<img width="768" alt="Screenshot 2022-03-04 at 15 06 01" src="https://user-images.githubusercontent.com/5569347/156779154-48d5c216-70ea-4ef2-8e18-8f02b1cde9dd.png">

<img width="911" alt="Screenshot 2022-03-04 at 15 07 13" src="https://user-images.githubusercontent.com/5569347/156779235-e0dcac64-69ca-4704-8701-f04feaf1ada7.png">

<img width="1023" alt="Screenshot 2022-03-04 at 15 07 53" src="https://user-images.githubusercontent.com/5569347/156779285-032975bf-429b-49da-8bfa-697882563adc.png">

2022-03-04 15:10 UTC, ashwini06 requested changes
Good job 👍🏼  

Just some general comments about the results from manta and delly. If we are going to only store and upload merged svdb results, do we need the annotation of manta/delly using vep and also existing rules for `bcftools_filter_delly` and `bcftools_filter_manta`?

2022-03-04 15:25 UTC, khurrammaqbool commented
> Good job 👍🏼
> 
> Just some general comments about the results from manta and delly. If we are going to only store and upload merged svdb results, do we need the annotation of manta/delly using vep and also existing rules for `bcftools_filter_delly` and `bcftools_filter_manta`?

I agree and already planned to handle it in next PR as the current only adds svdb.

2022-03-04 15:43 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
> +        get_threads(cluster_config, "svdb_merge_tumor_only")
I am waiting for the benchmarks.

2022-03-07 09:25 UTC, ivadym requested changes
The tags that BALSAMIC produces should be uniquely identified by Hermes. Some ways to do it: change the output variable name (which is included as a tag), use `svdb` as a wildcard or add an additional tag for the `housekeeper_id` variable.

2022-03-07 09:25 UTC, ivadym commented on BALSAMIC/snakemake_rules/annotation/varcaller_sv_wgs_filter_tumor_only.rule
> +    vcf_sv_pass = vep_dir + "SV.somatic.{case_name}.svdb.all.filtered.pass.vcf.gz",
```suggestion
    vcf_sv_pass_svdb = vep_dir + "SV.somatic.{case_name}.svdb.all.filtered.pass.vcf.gz",
```

2022-03-07 09:25 UTC, ivadym commented on BALSAMIC/snakemake_rules/annotation/varcaller_sv_wgs_filter_tumor_normal.rule
> +    vcf_sv_pass = vep_dir + "SV.somatic.{case_name}.svdb.all.filtered.pass.vcf.gz",
```suggestion
    vcf_sv_pass_svdb = vep_dir + "SV.somatic.{case_name}.svdb.all.filtered.pass.vcf.gz",
```

2022-03-07 10:31 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/annotation/varcaller_sv_wgs_filter_tumor_normal.rule
> +    var_caller = "svdb"
```suggestion

```

2022-03-07 10:31 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        var_caller = "svdb"
```suggestion

```

2022-03-07 10:34 UTC, ashwini06 requested changes
small fixes to adress

2022-03-07 13:52 UTC, ashwini06 approved these changes

2022-03-08 08:10 UTC, ivadym approved these changes
👍

2022-03-08 08:11 UTC, merged