feat: remove sv and cnv callers from annotation and filter rules
Clinical-Genomics/BALSAMIC pull request #889
Opened 2022-03-15 12:43 UTC by khurrammaqbool

### This PR:

Removed: sv and cnv callers from annotation and filter

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-03-15 13:19 UTC, khurrammaqbool commented
<img width="584" alt="Screenshot 2022-03-15 at 11 26 50" src="https://user-images.githubusercontent.com/5569347/158386211-274ff27c-9a99-480b-a8be-52fc3fca1643.png">
<img width="515" alt="Screenshot 2022-03-15 at 11 28 23" src="https://user-images.githubusercontent.com/5569347/158386243-a0e0ae69-dd26-4dcf-b3da-1903d09d3c98.png">
<img width="488" alt="Screenshot 2022-03-15 at 11 29 29" src="https://user-images.githubusercontent.com/5569347/158386325-427fe3e9-f66a-45d6-abdf-91631bc75d18.png">
<img width="497" alt="Screenshot 2022-03-15 at 11 30 14" src="https://user-images.githubusercontent.com/5569347/158386341-afdd3195-2afc-4be7-a245-b15027d2c042.png">

2022-03-16 09:15 UTC, ivadym requested changes
👍 

Just a minor comment from my part: the deleted rules should be removed from the `DELIVERY_RULES` constant in `workflow_rules.py`

```
DELIVERY_RULES = [
     ... ,
    "bcftools_filter_manta",
    "bcftools_filter_delly",
    "bcftools_filter_ascat",
    "bcftools_filter_cnvkit",
    ... ,
]
```

2022-03-16 09:15 UTC, ivadym commented on CHANGELOG.rst
> +* SV and CNVN callers from annotation and filtering #871
```suggestion
* SV and CNV callers from annotation and filtering #871
```

2022-03-16 10:36 UTC, khurrammaqbool commented
> 👍
> 
> Just a minor comment from my part:
> 
>     * The deleted rules should be removed from the `DELIVERY_RULES` constant in `workflow_rules.py`  and the `bcftools_filter_svdb` one included instead.
> 
> 
> ```
> DELIVERY_RULES = [
>      ... ,
>     "bcftools_filter_manta",
>     "bcftools_filter_delly",
>     "bcftools_filter_ascat",
>     "bcftools_filter_cnvkit",
>     ... ,
> ]
> ```

nice catch!

2022-03-16 10:37 UTC, khurrammaqbool commented on CHANGELOG.rst
> +* SV and CNVN callers from annotation and filtering #871
Thanks!

2022-03-16 12:40 UTC, ivadym approved these changes
👍 🥇

2022-03-16 12:47 UTC, merged

2022-03-16 12:57 UTC, ashwini06 commented
@khurrammaqbool : I was wondering if you had used the updated branch from develop for your branch `feat/remove_sv_vep`
Your panel outputs doesn't contain the newly added rule `vcf2cytosure_cnvkit` that was earlier merged with this [PR](https://github.com/Clinical-Genomics/BALSAMIC/pull/880)