fix: bcftools locked in annotate container
Clinical-Genomics/BALSAMIC pull request #909
Opened 2022-04-07 09:16 UTC by ashwini06

### This PR:

Fixes : #908 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-04-07 09:22 UTC, khurrammaqbool approved these changes

2022-04-07 09:22 UTC, khurrammaqbool commented on BALSAMIC/containers/annotate/annotate.yaml
> +  - bioconda::bcftools==1.10
- bioconda::bcftools=1.10

2022-04-11 08:44 UTC, ivadym requested changes

2022-04-11 08:44 UTC, ivadym commented on container_tests/annotate/annotate.sh
> +
This is not working as expected: since you are checking if the `tool_msg` is of length 0, all the `valid_commands` (even the ones with arbitrary names that does not exist in the binaries folder) will be evaluated as True with this parsing `| grep 'No'`.

<img width="836" alt="Screen Shot 2022-04-11 at 10 28 39" src="https://user-images.githubusercontent.com/26309194/162696449-fde8dbcf-b277-4ac1-9582-eccba3e1bd27.png">

Maybe this if statement could be combined with the previous implementation but I'm not sure if there is a good way to tests for dependencies as it could be hard to generalise it for all packages.

2022-04-11 10:37 UTC, ashwini06 commented on container_tests/annotate/annotate.sh
> +
Thanks for the suggestion @ivadym :) Update with new test

<img width="1403" alt="Screenshot 2022-04-11 at 12 26 27" src="https://user-images.githubusercontent.com/6302819/162723081-0a310e17-8694-4632-9bcd-b5893a108933.png">

2022-04-11 13:13 UTC, ivadym approved these changes
No further comments from my side 👍

2022-04-12 08:20 UTC, ashwini06 commented
Drop-in code coverage is due to the removal of pip installation of vcf2cytosure , which would remove coverage for this line https://app.codecov.io/gh/Clinical-Genomics/BALSAMIC/compare/909/changes#D1L475. But this is already addressed in develop branch in PR https://github.com/Clinical-Genomics/BALSAMIC/pull/869. Ignoring the drop and merging.

2022-04-12 08:21 UTC, merged