refactor: Update the list of files to be stored and delivered
Clinical-Genomics/BALSAMIC pull request #915
Opened 2022-04-19 10:09 UTC by ivadym

### This PR:

Updates the list of files that are generated and stored by BALSAMIC.

- Removed from `.hk` file: 
  - `fastp` rule:
    - `_1.fp.fastq.gz`
    - `_2.fp.fastq.gz`
    - `_fastp.json`
    - `_fastp.html`
  - `bcftools_filter_tnscope_tumor_only` rule:
    - `.tnscope_isec.all.filtered.vcf.gz`
  - `bcftools_filter_tnhaplotyper_tumor_normal` and  `bcftools_filter_tnhaplotyper_tumor_only` rules:
    - `.tnhaplotyper.all.filtered.vcf.gz`
    - `.tnhaplotyper.all.filtered.pass.vcf.gz`

- Made temporal:
  - `fastp` rule:
    - `_1.fp.fastq.gz`
    - `_2.fp.fastq.gz`
  - `fastp_umi` rule:
    - `_1.umi_optimized.fastq.gz`
    - `_2.umi_optimized.fastq.gz`

Hermes PR: https://github.com/Clinical-Genomics/hermes/issues/44

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-04-21 11:24 UTC, khurrammaqbool commented on BALSAMIC/constants/workflow_rules.py
> +    "vep_somatic_sv",
This should be replaced with svdb_merge_tumor_normal and svdb_merge_tumor_only. We decided to include raw VCFs and annotated filtered pass VCFs- vep_somatic_sv rule does not generate raw VCFs.

2022-04-21 11:24 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/annotation/vep.rule
> +    vcf_all_svdb = vep_dir + "SV.somatic.{case_name}.svdb.all.vcf.gz",
This file should be replaced with the one in vcf folder from the rules mentioned above.

2022-04-21 11:24 UTC, khurrammaqbool commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        plot_sunrise = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.sunrise.png",
The final pdf contains all these plots with the table. Isn't it better to deliver the pdf file instead?

2022-04-21 12:47 UTC, ashwini06 requested changes
@ivadym : Can you also please link the related Hermes PR to this PR.

2022-04-21 12:47 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        plot_sunrise = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.sunrise.png",
Indeed, good to deliver the final pdf.

2022-04-21 12:47 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/quality_control/fastp.rule
> -        housekeeper_id = {"id": "{sample}", "tags": "quality-trimmed-fastq"},
Can you also mark the `.umi_optimised.fastq.gz` and `.fp.fastq.gz` as temporary. Related to https://github.com/Clinical-Genomics/BALSAMIC/issues/911

2022-04-21 12:47 UTC, ashwini06 commented on BALSAMIC/constants/workflow_rules.py
> +    "vep_somatic_sv",
https://github.com/Clinical-Genomics/BALSAMIC/blob/ad13bdfaf5cdb8b754bae35c40d6c1f4a112f27d/BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule#L216

https://github.com/Clinical-Genomics/BALSAMIC/blob/ad13bdfaf5cdb8b754bae35c40d6c1f4a112f27d/BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule#L107

Inclusion of hk tags for these rules

2022-04-21 12:47 UTC, ashwini06 commented on BALSAMIC/constants/workflow_rules.py
> +    "vep_somatic_snv",
Inline to above changes, for somatic snvs it should follow the raww vcf deliverables from https://github.com/Clinical-Genomics/BALSAMIC/blob/ad13bdfaf5cdb8b754bae35c40d6c1f4a112f27d/BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule#L49 (panel), umi_panel https://github.com/Clinical-Genomics/BALSAMIC/blob/ad13bdfaf5cdb8b754bae35c40d6c1f4a112f27d/BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule#L7,   https://github.com/Clinical-Genomics/BALSAMIC/blob/ad13bdfaf5cdb8b754bae35c40d6c1f4a112f27d/BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule#L156 (wgs) . Same for T-only

2022-04-21 12:59 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
> +        plot_sunrise = vcf_dir + "CNV.somatic." + config["analysis"]["case_id"] + ".ascat.sunrise.png",
@ashwini06, @khurrammaqbool:

Adding a HK tag to these rules does not mean that this files will be delivered. The excel that I've shared with you contains that list.

The problem is that I added `ascat_tumor_normal` to the delivery rules lisT. However, `rule.py` does not support a `namedlist` as an input (generated by `expand(...)`), so it was crashing here:
 https://github.com/Clinical-Genomics/BALSAMIC/blob/8244f837388404d236611349d9eac4cb094290d1/BALSAMIC/utils/rule.py#L207

2022-04-21 15:31 UTC, ivadym commented
Linking the Hermes PR: https://github.com/Clinical-Genomics/hermes/issues/44

2022-04-22 07:16 UTC, ashwini06 commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
> +        housekeeper_id = {"id": config["analysis"]["case_id"], "tags": "research"},
```suggestion
        housekeeper_id = {"id": config["analysis"]["case_id"], "tags": "research"},
```
Is the tag here should be `research` or `clinical` ? Is there any documentation  to look up about these Hermes tags to describe what is `research` and `clinical`?

2022-04-22 07:18 UTC, ashwini06 commented
@ivadym : Is it possible to fix the tests for few of these missing lines? https://app.codecov.io/gh/Clinical-Genomics/BALSAMIC/compare/915/changes

2022-04-22 07:24 UTC, ivadym commented on BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
> +        housekeeper_id = {"id": config["analysis"]["case_id"], "tags": "research"},
The documentation in Hermes is a big vague: https://github.com/Clinical-Genomics/hermes/blob/14808b8ffa6b722ef1c603680e42f1eebe9237f9/cg_hermes/config/tags.py.

But I believe MIP follows this structure of defining the raw/annotated vcfs as `research` and the filtered ones as `clinical`.

2022-04-22 12:19 UTC, ivadym commented on BALSAMIC/constants/workflow_rules.py
> +    "tmb_calculation",
Done here: [d354b32](https://github.com/Clinical-Genomics/BALSAMIC/pull/915/commits/d354b328065991181d415007bf003175549b6316)

2022-04-28 10:08 UTC, ivadym commented
Quality control results:
```
/qc/sample_tumor_normal_wgs_metrics_deliverables.yaml
/qc/multiqc_report.html
/qc/multiqc_data/multiqc_data.json
```

Analysis specific results:

- TN-WGS
```
        /vep/SNV.germline.tumor.dnascope.vcf.gz
        /vep/SNV.germline.normal.dnascope.vcf.gz
        /vep/SV.germline.tumor.manta_germline.vcf.gz
        /vep/SV.germline.normal.manta_germline.vcf.gz
        /vcf/SNV.somatic.sample_tumor_normal_wgs.tnscope.vcf.gz
        /vcf/SNV.somatic.sample_tumor_normal_wgs.tnhaplotyper.vcf.gz
        /vcf/SV.somatic.sample_tumor_normal_wgs.svdb.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal_wgs.tnscope.all.filtered.pass.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal_wgs.tnhaplotyper.all.filtered.pass.vcf.gz
        /vep/SV.somatic.sample_tumor_normal_wgs.svdb.all.filtered.pass.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal_wgs.tnscope.balsamic_stat
        /vep/SNV.somatic.sample_tumor_normal_wgs.tnhaplotyper.balsamic_stat
        /vcf/CNV.somatic.sample_tumor_normal_wgs.ascat.output.pdf
        /vcf/CNV.somatic.sample_tumor_normal_wgs.ascat.copynumber.txt.gz
```

- TN-TGA
```
        /vep/SNV.germline.tumor.haplotypecaller.vcf.gz
        /vep/SNV.germline.normal.haplotypecaller.vcf.gz
        /vep/SNV.germline.tumor.dnascope.vcf.gz
        /vep/SNV.germline.normal.dnascope.vcf.gz
        /vep/SV.germline.tumor.manta_germline.vcf.gz
        /vep/SV.germline.normal.manta_germline.vcf.gz
        /vcf/SNV.somatic.sample_tumor_normal.TNscope_umi.vcf.gz
        /vcf/SNV.somatic.sample_tumor_normal.vardict.vcf.gz
        /vcf/SNV.somatic.sample_tumor_normal.tnhaplotyper.vcf.gz
        /vcf/SV.somatic.sample_tumor_normal.svdb.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal.TNscope_umi.all.filtered.pass.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal.vardict.all.filtered.pass.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal.tnhaplotyper.all.filtered.pass.vcf.gz
        /vep/SV.somatic.sample_tumor_normal.svdb.all.filtered.pass.vcf.gz
        /vep/SNV.somatic.sample_tumor_normal.vardict.balsamic_stat
        /vep/SNV.somatic.sample_tumor_normal.tnhaplotyper.balsamic_stat
        /vep/SNV.somatic.sample_tumor_normal.TNscope_umi.balsamic_stat
        /cnv/tumor.merged.cns
        /cnv/tumor.merged-diagram.pdf
        /cnv/tumor.merged-scatter.pdf
        /cnv/sample_tumor_normal.gene_metrics
        /vcf/CNV.somatic.sample_tumor_normal.cnvkit.vcf2cytosure.cgh
        /vep/SNV.somatic.sample_tumor_normal.vardict.all.filtered.pass.ranked.vcf.gz
        /qc/umi_qc/concatenated_normal_XXXXXX_R.umi.mean_family_depth
        /qc/umi_qc/concatenated_tumor_XXXXXX_R.umi.mean_family_depth
        /qc/umi_qc/sample_tumor_normal.TNscope_umi.AFtable.txt
```

2022-04-29 07:36 UTC, ivadym commented
Files and tags are parsed and generated as expected:

- WGS_TN

<img width="1151" alt="Screen Shot 2022-04-28 at 20 43 23" src="https://user-images.githubusercontent.com/26309194/165902653-82283c89-1fd4-4d94-a27e-59127fa0878c.png">

- TGA_TN

<img width="1150" alt="Screen Shot 2022-04-28 at 21 17 05" src="https://user-images.githubusercontent.com/26309194/165902662-780fd8c8-143d-4c50-81d1-15eaca9764b4.png">

2022-04-29 13:57 UTC, ashwini06 approved these changes
Looks good 🎇

2022-04-29 14:01 UTC, ashwini06 commented
> Files and tags are parsed and generated as expected:
> 
> * WGS_TN
> 
> <img alt="Screen Shot 2022-04-28 at 20 43 23" width="1151" src="https://user-images.githubusercontent.com/26309194/165902653-82283c89-1fd4-4d94-a27e-59127fa0878c.png">
> 
> * TGA_TN
> 
> <img alt="Screen Shot 2022-04-28 at 21 17 05" width="1150" src="https://user-images.githubusercontent.com/26309194/165902662-780fd8c8-143d-4c50-81d1-15eaca9764b4.png">

@ivadym What does the warning message "Cannot deliver step (rule) ..." refers to?

2022-04-29 18:00 UTC, ivadym commented
> @ivadym What does the warning message "Cannot deliver step (rule) ..." refers to?

It means that the rule it tries to deliver is not among the list of all the rules executed during the analysis.

If you notice we are going through all the rules that we are going to deliver. However, among all of them we can find some that are specific to the analysis type. Therefore, for `TN_WGS`, for example, you cannot find the rules associated with the UMIs.

https://github.com/Clinical-Genomics/BALSAMIC/blob/8244f837388404d236611349d9eac4cb094290d1/BALSAMIC/workflows/balsamic.smk#L299-L304

2022-04-30 09:27 UTC, khurrammaqbool reviewed
👍 . 
As we discussed, let's refactor to decouple delivery after this.

2022-04-30 09:28 UTC, khurrammaqbool approved these changes

2022-05-02 10:55 UTC, merged