Feat: balsamic UMI workflow solution
Clinical-Genomics/BALSAMIC pull request #932
Opened 2022-05-17 12:26 UTC by ashwini06

### This PR: 

Fixes: #896 

- Adds new `analysis_workflow` option to balsamic config case to run different workflows (`balsamic`, `balsamic_umi`)
- If `--analysis-workflow=balsamic` run only balsamic workflow, else if `--analysis-workflow=balsamic_umi` runs both balsamic+UMI workflow

*Test CommandLine*
```
# create config json for balsamic only analysis

balsamic config case --case-id TN_panel_balsamic --analysis-dir run_tests/ --balsamic-cache /home/proj/stage/cancer/balsamic_cache/ -t tests/test_data/fastq/S1_R_1.fastq.gz -n tests/test_data/fastq/S2_R_1.fastq.gz -p tests/test_data/references/panel/panel.bed -w balsamic

balsamic run analysis -s run_tests/ TN_panel_balsamic/TN_panel_balsamic.json

# create config json for balsamic+UMI  analysis

balsamic config case --case-id TN_panel_balsamic_umi --analysis-dir run_tests/ --balsamic-cache /home/proj/stage/cancer/balsamic_cache/ -t tests/test_data/fastq/S1_R_1.fastq.gz -n tests/test_data/fastq/S2_R_1.fastq.gz -p tests/test_data/references/panel/panel.bed -w balsamic_umi

balsamic run analysis -s run_tests/TN_panel_balsamic_umi/TN_panel_balsamic_umi.json

```

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-05-17 12:49 UTC, ashwini06 commented
balsamic dry-runs:

For Tonly_panel (Balsamic_only)


<img width="836" alt="Tonly_panel_balsamic" src="https://user-images.githubusercontent.com/6302819/168814254-e46d3ed2-7389-47fd-8276-977ac41e1a45.png">

For Tonly_panel (Balsamic + UMI)

<img width="593" alt="Tonly_panel_balsamic_umi" src="https://user-images.githubusercontent.com/6302819/168814264-dd84f324-4d71-4e46-a1b9-d04962f68f20.png">

For TN_panel (Balsamic only)

<img width="521" alt="TNpanel_balsamic" src="https://user-images.githubusercontent.com/6302819/168814297-74dbb2df-b48e-4ee9-8f07-fcfbd7f5b73e.png">

For TN_panel (Balsamic+UMI)

<img width="513" alt="TNpanel_balsamic_umi" src="https://user-images.githubusercontent.com/6302819/168814326-486c4ab3-cf65-41a0-be79-c7ca0b4a3cae.png">

2022-05-19 12:34 UTC, khurrammaqbool requested changes
It looks good. I have a minor suggestion related code readability.

2022-05-19 14:35 UTC, ashwini06 commented on BALSAMIC/commands/config/case.py
> +    "--analysis-workflow",
Thanks Khurram! I agree and thought about this existing constant`workflow_solution`https://github.com/Clinical-Genomics/BALSAMIC/blob/904d1837fa66163c31d0583d8bca987b07e100f7/BALSAMIC/constants/common.py#L40
But this option (`--workflow-solution`) is not used in `config case CLI`.  It is just a part of constant used within [balsamic.smk](https://github.com/Clinical-Genomics/BALSAMIC/blob/6f9d32e9a271a5c1290fe741dfd24ded50fa85ee/BALSAMIC/workflows/balsamic.smk#L137-L201)

Your suggestion to use `balsamic-umi-on and balsamic-umi-off ` instead of `analysis_workflow` might be too specific. I was thinking of expanding this `analysis_workflow` option for running other analysis snakemake workflows (for eg: balsamic_PON) in the future.

So  the thought process for running balsamic from production based on different analysis_workflow(balsamic/balsamic_umi/balsamic_pon) is : 
```
cg workflow balsamic start <case_id>
## executes
balsamic config case --case-id xx --analysis-dir xx --balsamic-cache xx -t xx -p xx --analysis-workflow balsamic
balsamic run analysis -s xx.json


cg worfklow balsamic-umi start <case_id>

balsamic config case --case-id xx --analysis-dir xx --balsamic-cache xx -t xx -p xx --analysis-workflow balsamic_umi
balsamic run analysis -s xx.json

cg workflow balsami-pon start <case_id>
# Executes and generate PON reference file in specific location on hasta 
balsamic config pon --case-id xx --analysis-dir xx --balsamic-cache xx --fastq_dir xx -p xx --analysis-workflow balsamic_pon 
balsamic run analysis -s xx.json
```

2022-05-20 14:15 UTC, rannick commented on BALSAMIC/commands/config/case.py
> +    "--analysis-workflow",
I agree with `--analysis_workflow` and will also use it for `balsamic-qc`. I think it makes cg commands clearer. Indeed `analysis_workflow` is close to `workflow_solution` but `workflow_solution` could be more specific, no? Because only the variant callers are influenced and not the rest of the pipeline. What about something like `calling_solution`?

2022-05-20 14:26 UTC, ashwini06 commented on BALSAMIC/commands/config/case.py
> +    "--analysis-workflow",
`workflow_solution` is just a constant name used within the balsamic.smk. If you think it could lead to confusion, we can change the name of it to something else. Like `calling_solution` or `variant_calling_solution`.

2022-05-20 14:30 UTC, rannick approved these changes

2022-05-20 14:30 UTC, rannick commented on BALSAMIC/commands/config/case.py
> +    "--analysis-workflow",
I don't think it needs to be changed, but if you want to change one of those, I vote for `workflow_solution`.

2022-05-23 14:28 UTC, ivadym approved these changes
👍

2022-05-23 15:04 UTC, merged