feat: Add provided gender to config file & update rules
Clinical-Genomics/BALSAMIC pull request #955
Opened 2022-06-13 10:03 UTC by ivadym

### This PR:

- Adds provided gender to config file
- Updates following rules including the provided gender as an input:
  - `vcf2cytosure_convert` (TO-PANEL)
  - `vcf2cytosure_convert_tumor_only`, `vcf2cytosure_convert_tumor_normal` (WGS)
  - `cnvkit_single`, `cnvkit_paired` (PANEL)
  - `ascat_tumor_normal` (TN-WGS)

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

2022-06-13 13:01 UTC, ivadym commented
### Tests:

- Dry run:

<img width="450" alt="Screen Shot 2022-06-13 at 15 01 06" src="https://user-images.githubusercontent.com/26309194/173359467-d140be7c-08fe-4ac7-bae3-746d79eeeb46.png">


- `config.json`

<img width="250" alt="Screen Shot 2022-06-13 at 14 59 35" src="https://user-images.githubusercontent.com/26309194/173359196-ccdca3cd-3409-4ddb-b902-c07ccc98a716.png">

2022-06-13 15:15 UTC, ashwini06 requested changes
Except for your changes to the `run_validate.sh`, the rest of the changes related to the gender option looks good  💯 
Unless no specific reason for changing this test script, I would suggest reverting it back to the original version

2022-06-13 15:21 UTC, ivadym commented on run_validate.sh
> +USAGE: [ -c _condaenv -m <run|config|all> -t <panel|WGS> -r ]
The `--analysis-type` flag has been removed:

> CHANGELOG.rst
>
> Removed cli --analysis_type for balsamic report deliver command and balsamic run analysis https://github.com/Clinical-Genomics/BALSAMIC/pull/942

2022-06-13 15:26 UTC, ashwini06 commented on run_validate.sh
> +USAGE: [ -c _condaenv -m <run|config|all> -t <panel|WGS> -r ]
Indeed, I forgot about that change 😜

2022-06-13 15:26 UTC, ashwini06 approved these changes

2022-06-17 07:57 UTC, ivadym commented
<img width="725" alt="Screen Shot 2022-06-17 at 09 57 30" src="https://user-images.githubusercontent.com/26309194/174253532-a14d10ac-75f1-4dea-8fb7-f817ec5b0b64.png">

2022-06-17 09:46 UTC, merged